(* Generated by rocq-of-rust *)
Require Import RocqOfRust.RocqOfRust.

Module background.
  (* StructRecord
    {
      name := "ToolMetadata";
      const_params := [];
      ty_params := [];
      fields :=
        [
          ("capabilities",
            Ty.apply
              (Ty.path "alloc::collections::btree::set::BTreeSet")
              []
              [ Ty.path "argus_kernel::capability::CapKind"; Ty.path "alloc::alloc::Global" ]);
          ("egress",
            Ty.apply
              (Ty.path "alloc::collections::btree::set::BTreeSet")
              []
              [ Ty.path "argus_kernel::types::EgressKind"; Ty.path "alloc::alloc::Global" ]);
          ("conf_floor", Ty.path "argus_kernel::types::ConfLevel");
          ("endorsed", Ty.path "bool")
        ];
    } *)
  
  Module Impl_core_clone_Clone_for_argus_kernel_background_ToolMetadata.
    Definition Self : Ty.t := Ty.path "argus_kernel::background::ToolMetadata".
    
    (* Clone *)
    Definition clone (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
      match ε, τ, α with
      | [], [], [ self ] =>
        ltac:(M.monadic
          (let self :=
            M.alloc (|
              Ty.apply (Ty.path "&") [] [ Ty.path "argus_kernel::background::ToolMetadata" ],
              self
            |) in
          Value.mkStructRecord
            "argus_kernel::background::ToolMetadata"
            []
            []
            [
              ("capabilities",
                M.call_closure (|
                  Ty.apply
                    (Ty.path "alloc::collections::btree::set::BTreeSet")
                    []
                    [ Ty.path "argus_kernel::capability::CapKind"; Ty.path "alloc::alloc::Global" ],
                  M.get_trait_method (|
                    "core::clone::Clone",
                    Ty.apply
                      (Ty.path "alloc::collections::btree::set::BTreeSet")
                      []
                      [ Ty.path "argus_kernel::capability::CapKind"; Ty.path "alloc::alloc::Global"
                      ],
                    [],
                    [],
                    "clone",
                    [],
                    []
                  |),
                  [
                    M.borrow (|
                      Pointer.Kind.Ref,
                      M.deref (|
                        M.borrow (|
                          Pointer.Kind.Ref,
                          M.SubPointer.get_struct_record_field (|
                            M.deref (| M.read (| self |) |),
                            "argus_kernel::background::ToolMetadata",
                            "capabilities"
                          |)
                        |)
                      |)
                    |)
                  ]
                |));
              ("egress",
                M.call_closure (|
                  Ty.apply
                    (Ty.path "alloc::collections::btree::set::BTreeSet")
                    []
                    [ Ty.path "argus_kernel::types::EgressKind"; Ty.path "alloc::alloc::Global" ],
                  M.get_trait_method (|
                    "core::clone::Clone",
                    Ty.apply
                      (Ty.path "alloc::collections::btree::set::BTreeSet")
                      []
                      [ Ty.path "argus_kernel::types::EgressKind"; Ty.path "alloc::alloc::Global" ],
                    [],
                    [],
                    "clone",
                    [],
                    []
                  |),
                  [
                    M.borrow (|
                      Pointer.Kind.Ref,
                      M.deref (|
                        M.borrow (|
                          Pointer.Kind.Ref,
                          M.SubPointer.get_struct_record_field (|
                            M.deref (| M.read (| self |) |),
                            "argus_kernel::background::ToolMetadata",
                            "egress"
                          |)
                        |)
                      |)
                    |)
                  ]
                |));
              ("conf_floor",
                M.call_closure (|
                  Ty.path "argus_kernel::types::ConfLevel",
                  M.get_trait_method (|
                    "core::clone::Clone",
                    Ty.path "argus_kernel::types::ConfLevel",
                    [],
                    [],
                    "clone",
                    [],
                    []
                  |),
                  [
                    M.borrow (|
                      Pointer.Kind.Ref,
                      M.deref (|
                        M.borrow (|
                          Pointer.Kind.Ref,
                          M.SubPointer.get_struct_record_field (|
                            M.deref (| M.read (| self |) |),
                            "argus_kernel::background::ToolMetadata",
                            "conf_floor"
                          |)
                        |)
                      |)
                    |)
                  ]
                |));
              ("endorsed",
                M.call_closure (|
                  Ty.path "bool",
                  M.get_trait_method (|
                    "core::clone::Clone",
                    Ty.path "bool",
                    [],
                    [],
                    "clone",
                    [],
                    []
                  |),
                  [
                    M.borrow (|
                      Pointer.Kind.Ref,
                      M.deref (|
                        M.borrow (|
                          Pointer.Kind.Ref,
                          M.SubPointer.get_struct_record_field (|
                            M.deref (| M.read (| self |) |),
                            "argus_kernel::background::ToolMetadata",
                            "endorsed"
                          |)
                        |)
                      |)
                    |)
                  ]
                |))
            ]))
      | _, _, _ => M.impossible "wrong number of arguments"
      end.
    
    Axiom Implements :
      M.IsTraitInstance
        "core::clone::Clone"
        (* Trait polymorphic consts *) []
        (* Trait polymorphic types *) []
        Self
        (* Instance *) [ ("clone", InstanceField.Method clone) ].
  End Impl_core_clone_Clone_for_argus_kernel_background_ToolMetadata.
  
  Module Impl_core_fmt_Debug_for_argus_kernel_background_ToolMetadata.
    Definition Self : Ty.t := Ty.path "argus_kernel::background::ToolMetadata".
    
    (* Debug *)
    Definition fmt (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
      match ε, τ, α with
      | [], [], [ self; f ] =>
        ltac:(M.monadic
          (let self :=
            M.alloc (|
              Ty.apply (Ty.path "&") [] [ Ty.path "argus_kernel::background::ToolMetadata" ],
              self
            |) in
          let f :=
            M.alloc (| Ty.apply (Ty.path "&mut") [] [ Ty.path "core::fmt::Formatter" ], f |) in
          M.call_closure (|
            Ty.apply
              (Ty.path "core::result::Result")
              []
              [ Ty.tuple []; Ty.path "core::fmt::Error" ],
            M.get_associated_function (|
              Ty.path "core::fmt::Formatter",
              "debug_struct_field4_finish",
              [],
              []
            |),
            [
              M.borrow (| Pointer.Kind.MutRef, M.deref (| M.read (| f |) |) |);
              M.borrow (| Pointer.Kind.Ref, M.deref (| mk_str (| "ToolMetadata" |) |) |);
              M.borrow (| Pointer.Kind.Ref, M.deref (| mk_str (| "capabilities" |) |) |);
              M.call_closure (|
                Ty.apply (Ty.path "&") [] [ Ty.dyn [ ("core::fmt::Debug::Trait", []) ] ],
                M.pointer_coercion
                  M.PointerCoercion.Unsize
                  (Ty.apply
                    (Ty.path "&")
                    []
                    [
                      Ty.apply
                        (Ty.path "alloc::collections::btree::set::BTreeSet")
                        []
                        [
                          Ty.path "argus_kernel::capability::CapKind";
                          Ty.path "alloc::alloc::Global"
                        ]
                    ])
                  (Ty.apply (Ty.path "&") [] [ Ty.dyn [ ("core::fmt::Debug::Trait", []) ] ]),
                [
                  M.borrow (|
                    Pointer.Kind.Ref,
                    M.deref (|
                      M.borrow (|
                        Pointer.Kind.Ref,
                        M.SubPointer.get_struct_record_field (|
                          M.deref (| M.read (| self |) |),
                          "argus_kernel::background::ToolMetadata",
                          "capabilities"
                        |)
                      |)
                    |)
                  |)
                ]
              |);
              M.borrow (| Pointer.Kind.Ref, M.deref (| mk_str (| "egress" |) |) |);
              M.call_closure (|
                Ty.apply (Ty.path "&") [] [ Ty.dyn [ ("core::fmt::Debug::Trait", []) ] ],
                M.pointer_coercion
                  M.PointerCoercion.Unsize
                  (Ty.apply
                    (Ty.path "&")
                    []
                    [
                      Ty.apply
                        (Ty.path "alloc::collections::btree::set::BTreeSet")
                        []
                        [ Ty.path "argus_kernel::types::EgressKind"; Ty.path "alloc::alloc::Global"
                        ]
                    ])
                  (Ty.apply (Ty.path "&") [] [ Ty.dyn [ ("core::fmt::Debug::Trait", []) ] ]),
                [
                  M.borrow (|
                    Pointer.Kind.Ref,
                    M.deref (|
                      M.borrow (|
                        Pointer.Kind.Ref,
                        M.SubPointer.get_struct_record_field (|
                          M.deref (| M.read (| self |) |),
                          "argus_kernel::background::ToolMetadata",
                          "egress"
                        |)
                      |)
                    |)
                  |)
                ]
              |);
              M.borrow (| Pointer.Kind.Ref, M.deref (| mk_str (| "conf_floor" |) |) |);
              M.call_closure (|
                Ty.apply (Ty.path "&") [] [ Ty.dyn [ ("core::fmt::Debug::Trait", []) ] ],
                M.pointer_coercion
                  M.PointerCoercion.Unsize
                  (Ty.apply (Ty.path "&") [] [ Ty.path "argus_kernel::types::ConfLevel" ])
                  (Ty.apply (Ty.path "&") [] [ Ty.dyn [ ("core::fmt::Debug::Trait", []) ] ]),
                [
                  M.borrow (|
                    Pointer.Kind.Ref,
                    M.deref (|
                      M.borrow (|
                        Pointer.Kind.Ref,
                        M.SubPointer.get_struct_record_field (|
                          M.deref (| M.read (| self |) |),
                          "argus_kernel::background::ToolMetadata",
                          "conf_floor"
                        |)
                      |)
                    |)
                  |)
                ]
              |);
              M.borrow (| Pointer.Kind.Ref, M.deref (| mk_str (| "endorsed" |) |) |);
              M.call_closure (|
                Ty.apply (Ty.path "&") [] [ Ty.dyn [ ("core::fmt::Debug::Trait", []) ] ],
                M.pointer_coercion
                  M.PointerCoercion.Unsize
                  (Ty.apply (Ty.path "&") [] [ Ty.apply (Ty.path "&") [] [ Ty.path "bool" ] ])
                  (Ty.apply (Ty.path "&") [] [ Ty.dyn [ ("core::fmt::Debug::Trait", []) ] ]),
                [
                  M.borrow (|
                    Pointer.Kind.Ref,
                    M.deref (|
                      M.borrow (|
                        Pointer.Kind.Ref,
                        M.alloc (|
                          Ty.apply (Ty.path "&") [] [ Ty.path "bool" ],
                          M.borrow (|
                            Pointer.Kind.Ref,
                            M.SubPointer.get_struct_record_field (|
                              M.deref (| M.read (| self |) |),
                              "argus_kernel::background::ToolMetadata",
                              "endorsed"
                            |)
                          |)
                        |)
                      |)
                    |)
                  |)
                ]
              |)
            ]
          |)))
      | _, _, _ => M.impossible "wrong number of arguments"
      end.
    
    Axiom Implements :
      M.IsTraitInstance
        "core::fmt::Debug"
        (* Trait polymorphic consts *) []
        (* Trait polymorphic types *) []
        Self
        (* Instance *) [ ("fmt", InstanceField.Method fmt) ].
  End Impl_core_fmt_Debug_for_argus_kernel_background_ToolMetadata.
  
  Module Impl_core_marker_StructuralPartialEq_for_argus_kernel_background_ToolMetadata.
    Definition Self : Ty.t := Ty.path "argus_kernel::background::ToolMetadata".
    
    Axiom Implements :
      M.IsTraitInstance
        "core::marker::StructuralPartialEq"
        (* Trait polymorphic consts *) []
        (* Trait polymorphic types *) []
        Self
        (* Instance *) [].
  End Impl_core_marker_StructuralPartialEq_for_argus_kernel_background_ToolMetadata.
  
  Module Impl_core_cmp_PartialEq_argus_kernel_background_ToolMetadata_for_argus_kernel_background_ToolMetadata.
    Definition Self : Ty.t := Ty.path "argus_kernel::background::ToolMetadata".
    
    (* PartialEq *)
    Definition eq (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
      match ε, τ, α with
      | [], [], [ self; other ] =>
        ltac:(M.monadic
          (let self :=
            M.alloc (|
              Ty.apply (Ty.path "&") [] [ Ty.path "argus_kernel::background::ToolMetadata" ],
              self
            |) in
          let other :=
            M.alloc (|
              Ty.apply (Ty.path "&") [] [ Ty.path "argus_kernel::background::ToolMetadata" ],
              other
            |) in
          LogicalOp.and (|
            LogicalOp.and (|
              LogicalOp.and (|
                M.call_closure (|
                  Ty.path "bool",
                  M.get_trait_method (|
                    "core::cmp::PartialEq",
                    Ty.apply
                      (Ty.path "alloc::collections::btree::set::BTreeSet")
                      []
                      [ Ty.path "argus_kernel::capability::CapKind"; Ty.path "alloc::alloc::Global"
                      ],
                    [],
                    [
                      Ty.apply
                        (Ty.path "alloc::collections::btree::set::BTreeSet")
                        []
                        [
                          Ty.path "argus_kernel::capability::CapKind";
                          Ty.path "alloc::alloc::Global"
                        ]
                    ],
                    "eq",
                    [],
                    []
                  |),
                  [
                    M.borrow (|
                      Pointer.Kind.Ref,
                      M.SubPointer.get_struct_record_field (|
                        M.deref (| M.read (| self |) |),
                        "argus_kernel::background::ToolMetadata",
                        "capabilities"
                      |)
                    |);
                    M.borrow (|
                      Pointer.Kind.Ref,
                      M.SubPointer.get_struct_record_field (|
                        M.deref (| M.read (| other |) |),
                        "argus_kernel::background::ToolMetadata",
                        "capabilities"
                      |)
                    |)
                  ]
                |),
                ltac:(M.monadic
                  (M.call_closure (|
                    Ty.path "bool",
                    M.get_trait_method (|
                      "core::cmp::PartialEq",
                      Ty.apply
                        (Ty.path "alloc::collections::btree::set::BTreeSet")
                        []
                        [ Ty.path "argus_kernel::types::EgressKind"; Ty.path "alloc::alloc::Global"
                        ],
                      [],
                      [
                        Ty.apply
                          (Ty.path "alloc::collections::btree::set::BTreeSet")
                          []
                          [
                            Ty.path "argus_kernel::types::EgressKind";
                            Ty.path "alloc::alloc::Global"
                          ]
                      ],
                      "eq",
                      [],
                      []
                    |),
                    [
                      M.borrow (|
                        Pointer.Kind.Ref,
                        M.SubPointer.get_struct_record_field (|
                          M.deref (| M.read (| self |) |),
                          "argus_kernel::background::ToolMetadata",
                          "egress"
                        |)
                      |);
                      M.borrow (|
                        Pointer.Kind.Ref,
                        M.SubPointer.get_struct_record_field (|
                          M.deref (| M.read (| other |) |),
                          "argus_kernel::background::ToolMetadata",
                          "egress"
                        |)
                      |)
                    ]
                  |)))
              |),
              ltac:(M.monadic
                (M.call_closure (|
                  Ty.path "bool",
                  M.get_trait_method (|
                    "core::cmp::PartialEq",
                    Ty.path "argus_kernel::types::ConfLevel",
                    [],
                    [ Ty.path "argus_kernel::types::ConfLevel" ],
                    "eq",
                    [],
                    []
                  |),
                  [
                    M.borrow (|
                      Pointer.Kind.Ref,
                      M.SubPointer.get_struct_record_field (|
                        M.deref (| M.read (| self |) |),
                        "argus_kernel::background::ToolMetadata",
                        "conf_floor"
                      |)
                    |);
                    M.borrow (|
                      Pointer.Kind.Ref,
                      M.SubPointer.get_struct_record_field (|
                        M.deref (| M.read (| other |) |),
                        "argus_kernel::background::ToolMetadata",
                        "conf_floor"
                      |)
                    |)
                  ]
                |)))
            |),
            ltac:(M.monadic
              (M.call_closure (|
                Ty.path "bool",
                BinOp.eq,
                [
                  M.read (|
                    M.SubPointer.get_struct_record_field (|
                      M.deref (| M.read (| self |) |),
                      "argus_kernel::background::ToolMetadata",
                      "endorsed"
                    |)
                  |);
                  M.read (|
                    M.SubPointer.get_struct_record_field (|
                      M.deref (| M.read (| other |) |),
                      "argus_kernel::background::ToolMetadata",
                      "endorsed"
                    |)
                  |)
                ]
              |)))
          |)))
      | _, _, _ => M.impossible "wrong number of arguments"
      end.
    
    Axiom Implements :
      M.IsTraitInstance
        "core::cmp::PartialEq"
        (* Trait polymorphic consts *) []
        (* Trait polymorphic types *) [ Ty.path "argus_kernel::background::ToolMetadata" ]
        Self
        (* Instance *) [ ("eq", InstanceField.Method eq) ].
  End Impl_core_cmp_PartialEq_argus_kernel_background_ToolMetadata_for_argus_kernel_background_ToolMetadata.
  
  Module Impl_core_cmp_Eq_for_argus_kernel_background_ToolMetadata.
    Definition Self : Ty.t := Ty.path "argus_kernel::background::ToolMetadata".
    
    (* Eq *)
    Definition assert_receiver_is_total_eq
        (ε : list Value.t)
        (τ : list Ty.t)
        (α : list Value.t)
        : M :=
      match ε, τ, α with
      | [], [], [ self ] =>
        ltac:(M.monadic
          (let self :=
            M.alloc (|
              Ty.apply (Ty.path "&") [] [ Ty.path "argus_kernel::background::ToolMetadata" ],
              self
            |) in
          M.match_operator (|
            Ty.tuple [],
            Value.DeclaredButUndefined,
            [
              fun γ =>
                ltac:(M.monadic
                  (M.match_operator (|
                    Ty.tuple [],
                    Value.DeclaredButUndefined,
                    [
                      fun γ =>
                        ltac:(M.monadic
                          (M.match_operator (|
                            Ty.tuple [],
                            Value.DeclaredButUndefined,
                            [
                              fun γ =>
                                ltac:(M.monadic
                                  (M.match_operator (|
                                    Ty.tuple [],
                                    Value.DeclaredButUndefined,
                                    [ fun γ => ltac:(M.monadic (Value.Tuple [])) ]
                                  |)))
                            ]
                          |)))
                    ]
                  |)))
            ]
          |)))
      | _, _, _ => M.impossible "wrong number of arguments"
      end.
    
    Axiom Implements :
      M.IsTraitInstance
        "core::cmp::Eq"
        (* Trait polymorphic consts *) []
        (* Trait polymorphic types *) []
        Self
        (* Instance *)
        [ ("assert_receiver_is_total_eq", InstanceField.Method assert_receiver_is_total_eq) ].
  End Impl_core_cmp_Eq_for_argus_kernel_background_ToolMetadata.
  
  (*
  Enum FlowMode
  {
    const_params := [];
    ty_params := [];
    variants :=
      [
        {
          name := "Allow";
          item := StructTuple [];
        };
        {
          name := "Inspect";
          item := StructTuple [];
        };
        {
          name := "Deny";
          item := StructTuple [];
        }
      ];
  }
  *)
  
  Axiom IsDiscriminant_FlowMode_Allow :
    M.IsDiscriminant "argus_kernel::background::FlowMode::Allow" 0.
  Axiom IsDiscriminant_FlowMode_Inspect :
    M.IsDiscriminant "argus_kernel::background::FlowMode::Inspect" 1.
  Axiom IsDiscriminant_FlowMode_Deny :
    M.IsDiscriminant "argus_kernel::background::FlowMode::Deny" 2.
  
  Module Impl_core_clone_Clone_for_argus_kernel_background_FlowMode.
    Definition Self : Ty.t := Ty.path "argus_kernel::background::FlowMode".
    
    (* Clone *)
    Definition clone (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
      match ε, τ, α with
      | [], [], [ self ] =>
        ltac:(M.monadic
          (let self :=
            M.alloc (|
              Ty.apply (Ty.path "&") [] [ Ty.path "argus_kernel::background::FlowMode" ],
              self
            |) in
          M.read (| M.deref (| M.read (| self |) |) |)))
      | _, _, _ => M.impossible "wrong number of arguments"
      end.
    
    Axiom Implements :
      M.IsTraitInstance
        "core::clone::Clone"
        (* Trait polymorphic consts *) []
        (* Trait polymorphic types *) []
        Self
        (* Instance *) [ ("clone", InstanceField.Method clone) ].
  End Impl_core_clone_Clone_for_argus_kernel_background_FlowMode.
  
  Module Impl_core_marker_Copy_for_argus_kernel_background_FlowMode.
    Definition Self : Ty.t := Ty.path "argus_kernel::background::FlowMode".
    
    Axiom Implements :
      M.IsTraitInstance
        "core::marker::Copy"
        (* Trait polymorphic consts *) []
        (* Trait polymorphic types *) []
        Self
        (* Instance *) [].
  End Impl_core_marker_Copy_for_argus_kernel_background_FlowMode.
  
  Module Impl_core_fmt_Debug_for_argus_kernel_background_FlowMode.
    Definition Self : Ty.t := Ty.path "argus_kernel::background::FlowMode".
    
    (* Debug *)
    Definition fmt (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
      match ε, τ, α with
      | [], [], [ self; f ] =>
        ltac:(M.monadic
          (let self :=
            M.alloc (|
              Ty.apply (Ty.path "&") [] [ Ty.path "argus_kernel::background::FlowMode" ],
              self
            |) in
          let f :=
            M.alloc (| Ty.apply (Ty.path "&mut") [] [ Ty.path "core::fmt::Formatter" ], f |) in
          M.call_closure (|
            Ty.apply
              (Ty.path "core::result::Result")
              []
              [ Ty.tuple []; Ty.path "core::fmt::Error" ],
            M.get_associated_function (| Ty.path "core::fmt::Formatter", "write_str", [], [] |),
            [
              M.borrow (| Pointer.Kind.MutRef, M.deref (| M.read (| f |) |) |);
              M.match_operator (|
                Ty.apply (Ty.path "&") [] [ Ty.path "str" ],
                self,
                [
                  fun γ =>
                    ltac:(M.monadic
                      (let γ := M.deref (| M.read (| γ |) |) in
                      let _ :=
                        M.is_struct_tuple (| γ, "argus_kernel::background::FlowMode::Allow" |) in
                      M.borrow (| Pointer.Kind.Ref, M.deref (| mk_str (| "Allow" |) |) |)));
                  fun γ =>
                    ltac:(M.monadic
                      (let γ := M.deref (| M.read (| γ |) |) in
                      let _ :=
                        M.is_struct_tuple (| γ, "argus_kernel::background::FlowMode::Inspect" |) in
                      M.borrow (| Pointer.Kind.Ref, M.deref (| mk_str (| "Inspect" |) |) |)));
                  fun γ =>
                    ltac:(M.monadic
                      (let γ := M.deref (| M.read (| γ |) |) in
                      let _ :=
                        M.is_struct_tuple (| γ, "argus_kernel::background::FlowMode::Deny" |) in
                      M.borrow (| Pointer.Kind.Ref, M.deref (| mk_str (| "Deny" |) |) |)))
                ]
              |)
            ]
          |)))
      | _, _, _ => M.impossible "wrong number of arguments"
      end.
    
    Axiom Implements :
      M.IsTraitInstance
        "core::fmt::Debug"
        (* Trait polymorphic consts *) []
        (* Trait polymorphic types *) []
        Self
        (* Instance *) [ ("fmt", InstanceField.Method fmt) ].
  End Impl_core_fmt_Debug_for_argus_kernel_background_FlowMode.
  
  Module Impl_core_marker_StructuralPartialEq_for_argus_kernel_background_FlowMode.
    Definition Self : Ty.t := Ty.path "argus_kernel::background::FlowMode".
    
    Axiom Implements :
      M.IsTraitInstance
        "core::marker::StructuralPartialEq"
        (* Trait polymorphic consts *) []
        (* Trait polymorphic types *) []
        Self
        (* Instance *) [].
  End Impl_core_marker_StructuralPartialEq_for_argus_kernel_background_FlowMode.
  
  Module Impl_core_cmp_PartialEq_argus_kernel_background_FlowMode_for_argus_kernel_background_FlowMode.
    Definition Self : Ty.t := Ty.path "argus_kernel::background::FlowMode".
    
    (* PartialEq *)
    Definition eq (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
      match ε, τ, α with
      | [], [], [ self; other ] =>
        ltac:(M.monadic
          (let self :=
            M.alloc (|
              Ty.apply (Ty.path "&") [] [ Ty.path "argus_kernel::background::FlowMode" ],
              self
            |) in
          let other :=
            M.alloc (|
              Ty.apply (Ty.path "&") [] [ Ty.path "argus_kernel::background::FlowMode" ],
              other
            |) in
          M.read (|
            let~ __self_discr : Ty.path "isize" :=
              M.call_closure (|
                Ty.path "isize",
                M.get_function (|
                  "core::intrinsics::discriminant_value",
                  [],
                  [ Ty.path "argus_kernel::background::FlowMode" ]
                |),
                [ M.borrow (| Pointer.Kind.Ref, M.deref (| M.read (| self |) |) |) ]
              |) in
            let~ __arg1_discr : Ty.path "isize" :=
              M.call_closure (|
                Ty.path "isize",
                M.get_function (|
                  "core::intrinsics::discriminant_value",
                  [],
                  [ Ty.path "argus_kernel::background::FlowMode" ]
                |),
                [ M.borrow (| Pointer.Kind.Ref, M.deref (| M.read (| other |) |) |) ]
              |) in
            M.alloc (|
              Ty.path "bool",
              M.call_closure (|
                Ty.path "bool",
                BinOp.eq,
                [ M.read (| __self_discr |); M.read (| __arg1_discr |) ]
              |)
            |)
          |)))
      | _, _, _ => M.impossible "wrong number of arguments"
      end.
    
    Axiom Implements :
      M.IsTraitInstance
        "core::cmp::PartialEq"
        (* Trait polymorphic consts *) []
        (* Trait polymorphic types *) [ Ty.path "argus_kernel::background::FlowMode" ]
        Self
        (* Instance *) [ ("eq", InstanceField.Method eq) ].
  End Impl_core_cmp_PartialEq_argus_kernel_background_FlowMode_for_argus_kernel_background_FlowMode.
  
  Module Impl_core_cmp_Eq_for_argus_kernel_background_FlowMode.
    Definition Self : Ty.t := Ty.path "argus_kernel::background::FlowMode".
    
    (* Eq *)
    Definition assert_receiver_is_total_eq
        (ε : list Value.t)
        (τ : list Ty.t)
        (α : list Value.t)
        : M :=
      match ε, τ, α with
      | [], [], [ self ] =>
        ltac:(M.monadic
          (let self :=
            M.alloc (|
              Ty.apply (Ty.path "&") [] [ Ty.path "argus_kernel::background::FlowMode" ],
              self
            |) in
          Value.Tuple []))
      | _, _, _ => M.impossible "wrong number of arguments"
      end.
    
    Axiom Implements :
      M.IsTraitInstance
        "core::cmp::Eq"
        (* Trait polymorphic consts *) []
        (* Trait polymorphic types *) []
        Self
        (* Instance *)
        [ ("assert_receiver_is_total_eq", InstanceField.Method assert_receiver_is_total_eq) ].
  End Impl_core_cmp_Eq_for_argus_kernel_background_FlowMode.
  
  (* StructRecord
    {
      name := "BackgroundTheory";
      const_params := [];
      ty_params := [];
      fields :=
        [
          ("tools",
            Ty.apply
              (Ty.path "alloc::collections::btree::map::BTreeMap")
              []
              [
                Ty.path "argus_kernel::types::ToolId";
                Ty.path "argus_kernel::background::ToolMetadata";
                Ty.path "alloc::alloc::Global"
              ]);
          ("flow_policy",
            Ty.apply
              (Ty.path "alloc::collections::btree::map::BTreeMap")
              []
              [
                Ty.tuple
                  [
                    Ty.path "argus_kernel::types::ConfLevel";
                    Ty.path "argus_kernel::types::EgressKind"
                  ];
                Ty.path "argus_kernel::background::FlowMode";
                Ty.path "alloc::alloc::Global"
              ]);
          ("flow_overrides",
            Ty.apply
              (Ty.path "alloc::collections::btree::set::BTreeSet")
              []
              [
                Ty.tuple
                  [
                    Ty.path "argus_kernel::types::AgentId";
                    Ty.path "argus_kernel::types::ToolId";
                    Ty.path "argus_kernel::types::ConfLevel"
                  ];
                Ty.path "alloc::alloc::Global"
              ])
        ];
    } *)
  
  Module Impl_core_clone_Clone_for_argus_kernel_background_BackgroundTheory.
    Definition Self : Ty.t := Ty.path "argus_kernel::background::BackgroundTheory".
    
    (* Clone *)
    Definition clone (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
      match ε, τ, α with
      | [], [], [ self ] =>
        ltac:(M.monadic
          (let self :=
            M.alloc (|
              Ty.apply (Ty.path "&") [] [ Ty.path "argus_kernel::background::BackgroundTheory" ],
              self
            |) in
          Value.mkStructRecord
            "argus_kernel::background::BackgroundTheory"
            []
            []
            [
              ("tools",
                M.call_closure (|
                  Ty.apply
                    (Ty.path "alloc::collections::btree::map::BTreeMap")
                    []
                    [
                      Ty.path "argus_kernel::types::ToolId";
                      Ty.path "argus_kernel::background::ToolMetadata";
                      Ty.path "alloc::alloc::Global"
                    ],
                  M.get_trait_method (|
                    "core::clone::Clone",
                    Ty.apply
                      (Ty.path "alloc::collections::btree::map::BTreeMap")
                      []
                      [
                        Ty.path "argus_kernel::types::ToolId";
                        Ty.path "argus_kernel::background::ToolMetadata";
                        Ty.path "alloc::alloc::Global"
                      ],
                    [],
                    [],
                    "clone",
                    [],
                    []
                  |),
                  [
                    M.borrow (|
                      Pointer.Kind.Ref,
                      M.deref (|
                        M.borrow (|
                          Pointer.Kind.Ref,
                          M.SubPointer.get_struct_record_field (|
                            M.deref (| M.read (| self |) |),
                            "argus_kernel::background::BackgroundTheory",
                            "tools"
                          |)
                        |)
                      |)
                    |)
                  ]
                |));
              ("flow_policy",
                M.call_closure (|
                  Ty.apply
                    (Ty.path "alloc::collections::btree::map::BTreeMap")
                    []
                    [
                      Ty.tuple
                        [
                          Ty.path "argus_kernel::types::ConfLevel";
                          Ty.path "argus_kernel::types::EgressKind"
                        ];
                      Ty.path "argus_kernel::background::FlowMode";
                      Ty.path "alloc::alloc::Global"
                    ],
                  M.get_trait_method (|
                    "core::clone::Clone",
                    Ty.apply
                      (Ty.path "alloc::collections::btree::map::BTreeMap")
                      []
                      [
                        Ty.tuple
                          [
                            Ty.path "argus_kernel::types::ConfLevel";
                            Ty.path "argus_kernel::types::EgressKind"
                          ];
                        Ty.path "argus_kernel::background::FlowMode";
                        Ty.path "alloc::alloc::Global"
                      ],
                    [],
                    [],
                    "clone",
                    [],
                    []
                  |),
                  [
                    M.borrow (|
                      Pointer.Kind.Ref,
                      M.deref (|
                        M.borrow (|
                          Pointer.Kind.Ref,
                          M.SubPointer.get_struct_record_field (|
                            M.deref (| M.read (| self |) |),
                            "argus_kernel::background::BackgroundTheory",
                            "flow_policy"
                          |)
                        |)
                      |)
                    |)
                  ]
                |));
              ("flow_overrides",
                M.call_closure (|
                  Ty.apply
                    (Ty.path "alloc::collections::btree::set::BTreeSet")
                    []
                    [
                      Ty.tuple
                        [
                          Ty.path "argus_kernel::types::AgentId";
                          Ty.path "argus_kernel::types::ToolId";
                          Ty.path "argus_kernel::types::ConfLevel"
                        ];
                      Ty.path "alloc::alloc::Global"
                    ],
                  M.get_trait_method (|
                    "core::clone::Clone",
                    Ty.apply
                      (Ty.path "alloc::collections::btree::set::BTreeSet")
                      []
                      [
                        Ty.tuple
                          [
                            Ty.path "argus_kernel::types::AgentId";
                            Ty.path "argus_kernel::types::ToolId";
                            Ty.path "argus_kernel::types::ConfLevel"
                          ];
                        Ty.path "alloc::alloc::Global"
                      ],
                    [],
                    [],
                    "clone",
                    [],
                    []
                  |),
                  [
                    M.borrow (|
                      Pointer.Kind.Ref,
                      M.deref (|
                        M.borrow (|
                          Pointer.Kind.Ref,
                          M.SubPointer.get_struct_record_field (|
                            M.deref (| M.read (| self |) |),
                            "argus_kernel::background::BackgroundTheory",
                            "flow_overrides"
                          |)
                        |)
                      |)
                    |)
                  ]
                |))
            ]))
      | _, _, _ => M.impossible "wrong number of arguments"
      end.
    
    Axiom Implements :
      M.IsTraitInstance
        "core::clone::Clone"
        (* Trait polymorphic consts *) []
        (* Trait polymorphic types *) []
        Self
        (* Instance *) [ ("clone", InstanceField.Method clone) ].
  End Impl_core_clone_Clone_for_argus_kernel_background_BackgroundTheory.
  
  Module Impl_core_fmt_Debug_for_argus_kernel_background_BackgroundTheory.
    Definition Self : Ty.t := Ty.path "argus_kernel::background::BackgroundTheory".
    
    (* Debug *)
    Definition fmt (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
      match ε, τ, α with
      | [], [], [ self; f ] =>
        ltac:(M.monadic
          (let self :=
            M.alloc (|
              Ty.apply (Ty.path "&") [] [ Ty.path "argus_kernel::background::BackgroundTheory" ],
              self
            |) in
          let f :=
            M.alloc (| Ty.apply (Ty.path "&mut") [] [ Ty.path "core::fmt::Formatter" ], f |) in
          M.call_closure (|
            Ty.apply
              (Ty.path "core::result::Result")
              []
              [ Ty.tuple []; Ty.path "core::fmt::Error" ],
            M.get_associated_function (|
              Ty.path "core::fmt::Formatter",
              "debug_struct_field3_finish",
              [],
              []
            |),
            [
              M.borrow (| Pointer.Kind.MutRef, M.deref (| M.read (| f |) |) |);
              M.borrow (| Pointer.Kind.Ref, M.deref (| mk_str (| "BackgroundTheory" |) |) |);
              M.borrow (| Pointer.Kind.Ref, M.deref (| mk_str (| "tools" |) |) |);
              M.call_closure (|
                Ty.apply (Ty.path "&") [] [ Ty.dyn [ ("core::fmt::Debug::Trait", []) ] ],
                M.pointer_coercion
                  M.PointerCoercion.Unsize
                  (Ty.apply
                    (Ty.path "&")
                    []
                    [
                      Ty.apply
                        (Ty.path "alloc::collections::btree::map::BTreeMap")
                        []
                        [
                          Ty.path "argus_kernel::types::ToolId";
                          Ty.path "argus_kernel::background::ToolMetadata";
                          Ty.path "alloc::alloc::Global"
                        ]
                    ])
                  (Ty.apply (Ty.path "&") [] [ Ty.dyn [ ("core::fmt::Debug::Trait", []) ] ]),
                [
                  M.borrow (|
                    Pointer.Kind.Ref,
                    M.deref (|
                      M.borrow (|
                        Pointer.Kind.Ref,
                        M.SubPointer.get_struct_record_field (|
                          M.deref (| M.read (| self |) |),
                          "argus_kernel::background::BackgroundTheory",
                          "tools"
                        |)
                      |)
                    |)
                  |)
                ]
              |);
              M.borrow (| Pointer.Kind.Ref, M.deref (| mk_str (| "flow_policy" |) |) |);
              M.call_closure (|
                Ty.apply (Ty.path "&") [] [ Ty.dyn [ ("core::fmt::Debug::Trait", []) ] ],
                M.pointer_coercion
                  M.PointerCoercion.Unsize
                  (Ty.apply
                    (Ty.path "&")
                    []
                    [
                      Ty.apply
                        (Ty.path "alloc::collections::btree::map::BTreeMap")
                        []
                        [
                          Ty.tuple
                            [
                              Ty.path "argus_kernel::types::ConfLevel";
                              Ty.path "argus_kernel::types::EgressKind"
                            ];
                          Ty.path "argus_kernel::background::FlowMode";
                          Ty.path "alloc::alloc::Global"
                        ]
                    ])
                  (Ty.apply (Ty.path "&") [] [ Ty.dyn [ ("core::fmt::Debug::Trait", []) ] ]),
                [
                  M.borrow (|
                    Pointer.Kind.Ref,
                    M.deref (|
                      M.borrow (|
                        Pointer.Kind.Ref,
                        M.SubPointer.get_struct_record_field (|
                          M.deref (| M.read (| self |) |),
                          "argus_kernel::background::BackgroundTheory",
                          "flow_policy"
                        |)
                      |)
                    |)
                  |)
                ]
              |);
              M.borrow (| Pointer.Kind.Ref, M.deref (| mk_str (| "flow_overrides" |) |) |);
              M.call_closure (|
                Ty.apply (Ty.path "&") [] [ Ty.dyn [ ("core::fmt::Debug::Trait", []) ] ],
                M.pointer_coercion
                  M.PointerCoercion.Unsize
                  (Ty.apply
                    (Ty.path "&")
                    []
                    [
                      Ty.apply
                        (Ty.path "&")
                        []
                        [
                          Ty.apply
                            (Ty.path "alloc::collections::btree::set::BTreeSet")
                            []
                            [
                              Ty.tuple
                                [
                                  Ty.path "argus_kernel::types::AgentId";
                                  Ty.path "argus_kernel::types::ToolId";
                                  Ty.path "argus_kernel::types::ConfLevel"
                                ];
                              Ty.path "alloc::alloc::Global"
                            ]
                        ]
                    ])
                  (Ty.apply (Ty.path "&") [] [ Ty.dyn [ ("core::fmt::Debug::Trait", []) ] ]),
                [
                  M.borrow (|
                    Pointer.Kind.Ref,
                    M.deref (|
                      M.borrow (|
                        Pointer.Kind.Ref,
                        M.alloc (|
                          Ty.apply
                            (Ty.path "&")
                            []
                            [
                              Ty.apply
                                (Ty.path "alloc::collections::btree::set::BTreeSet")
                                []
                                [
                                  Ty.tuple
                                    [
                                      Ty.path "argus_kernel::types::AgentId";
                                      Ty.path "argus_kernel::types::ToolId";
                                      Ty.path "argus_kernel::types::ConfLevel"
                                    ];
                                  Ty.path "alloc::alloc::Global"
                                ]
                            ],
                          M.borrow (|
                            Pointer.Kind.Ref,
                            M.SubPointer.get_struct_record_field (|
                              M.deref (| M.read (| self |) |),
                              "argus_kernel::background::BackgroundTheory",
                              "flow_overrides"
                            |)
                          |)
                        |)
                      |)
                    |)
                  |)
                ]
              |)
            ]
          |)))
      | _, _, _ => M.impossible "wrong number of arguments"
      end.
    
    Axiom Implements :
      M.IsTraitInstance
        "core::fmt::Debug"
        (* Trait polymorphic consts *) []
        (* Trait polymorphic types *) []
        Self
        (* Instance *) [ ("fmt", InstanceField.Method fmt) ].
  End Impl_core_fmt_Debug_for_argus_kernel_background_BackgroundTheory.
  
  Module Impl_argus_kernel_background_BackgroundTheory.
    Definition Self : Ty.t := Ty.path "argus_kernel::background::BackgroundTheory".
    
    (*
        pub fn has_tool(&self, tool: &ToolId) -> bool {
            self.tools.contains_key(tool)
        }
    *)
    Definition has_tool (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
      match ε, τ, α with
      | [], [], [ self; tool ] =>
        ltac:(M.monadic
          (let self :=
            M.alloc (|
              Ty.apply (Ty.path "&") [] [ Ty.path "argus_kernel::background::BackgroundTheory" ],
              self
            |) in
          let tool :=
            M.alloc (|
              Ty.apply (Ty.path "&") [] [ Ty.path "argus_kernel::types::ToolId" ],
              tool
            |) in
          M.call_closure (|
            Ty.path "bool",
            M.get_associated_function (|
              Ty.apply
                (Ty.path "alloc::collections::btree::map::BTreeMap")
                []
                [
                  Ty.path "argus_kernel::types::ToolId";
                  Ty.path "argus_kernel::background::ToolMetadata";
                  Ty.path "alloc::alloc::Global"
                ],
              "contains_key",
              [],
              [ Ty.path "argus_kernel::types::ToolId" ]
            |),
            [
              M.borrow (|
                Pointer.Kind.Ref,
                M.SubPointer.get_struct_record_field (|
                  M.deref (| M.read (| self |) |),
                  "argus_kernel::background::BackgroundTheory",
                  "tools"
                |)
              |);
              M.borrow (| Pointer.Kind.Ref, M.deref (| M.read (| tool |) |) |)
            ]
          |)))
      | _, _, _ => M.impossible "wrong number of arguments"
      end.
    
    Global Instance AssociatedFunction_has_tool : M.IsAssociatedFunction.C Self "has_tool" has_tool.
    Admitted.
    Global Typeclasses Opaque has_tool.
    
    (*
        pub fn tool_metadata(&self, tool: &ToolId) -> Option<&ToolMetadata> {
            self.tools.get(tool)
        }
    *)
    Definition tool_metadata (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
      match ε, τ, α with
      | [], [], [ self; tool ] =>
        ltac:(M.monadic
          (let self :=
            M.alloc (|
              Ty.apply (Ty.path "&") [] [ Ty.path "argus_kernel::background::BackgroundTheory" ],
              self
            |) in
          let tool :=
            M.alloc (|
              Ty.apply (Ty.path "&") [] [ Ty.path "argus_kernel::types::ToolId" ],
              tool
            |) in
          M.call_closure (|
            Ty.apply
              (Ty.path "core::option::Option")
              []
              [ Ty.apply (Ty.path "&") [] [ Ty.path "argus_kernel::background::ToolMetadata" ] ],
            M.get_associated_function (|
              Ty.apply
                (Ty.path "alloc::collections::btree::map::BTreeMap")
                []
                [
                  Ty.path "argus_kernel::types::ToolId";
                  Ty.path "argus_kernel::background::ToolMetadata";
                  Ty.path "alloc::alloc::Global"
                ],
              "get",
              [],
              [ Ty.path "argus_kernel::types::ToolId" ]
            |),
            [
              M.borrow (|
                Pointer.Kind.Ref,
                M.SubPointer.get_struct_record_field (|
                  M.deref (| M.read (| self |) |),
                  "argus_kernel::background::BackgroundTheory",
                  "tools"
                |)
              |);
              M.borrow (| Pointer.Kind.Ref, M.deref (| M.read (| tool |) |) |)
            ]
          |)))
      | _, _, _ => M.impossible "wrong number of arguments"
      end.
    
    Global Instance AssociatedFunction_tool_metadata :
      M.IsAssociatedFunction.C Self "tool_metadata" tool_metadata.
    Admitted.
    Global Typeclasses Opaque tool_metadata.
    
    (*
        pub fn flow_mode(&self, level: ConfLevel, egress: EgressKind) -> FlowMode {
            self.flow_policy
                .get(&(level, egress))
                .copied()
                .unwrap_or(FlowMode::Deny)
        }
    *)
    Definition flow_mode (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
      match ε, τ, α with
      | [], [], [ self; level; egress ] =>
        ltac:(M.monadic
          (let self :=
            M.alloc (|
              Ty.apply (Ty.path "&") [] [ Ty.path "argus_kernel::background::BackgroundTheory" ],
              self
            |) in
          let level := M.alloc (| Ty.path "argus_kernel::types::ConfLevel", level |) in
          let egress := M.alloc (| Ty.path "argus_kernel::types::EgressKind", egress |) in
          M.call_closure (|
            Ty.path "argus_kernel::background::FlowMode",
            M.get_associated_function (|
              Ty.apply
                (Ty.path "core::option::Option")
                []
                [ Ty.path "argus_kernel::background::FlowMode" ],
              "unwrap_or",
              [],
              []
            |),
            [
              M.call_closure (|
                Ty.apply
                  (Ty.path "core::option::Option")
                  []
                  [ Ty.path "argus_kernel::background::FlowMode" ],
                M.get_associated_function (|
                  Ty.apply
                    (Ty.path "core::option::Option")
                    []
                    [ Ty.apply (Ty.path "&") [] [ Ty.path "argus_kernel::background::FlowMode" ] ],
                  "copied",
                  [],
                  []
                |),
                [
                  M.call_closure (|
                    Ty.apply
                      (Ty.path "core::option::Option")
                      []
                      [ Ty.apply (Ty.path "&") [] [ Ty.path "argus_kernel::background::FlowMode" ]
                      ],
                    M.get_associated_function (|
                      Ty.apply
                        (Ty.path "alloc::collections::btree::map::BTreeMap")
                        []
                        [
                          Ty.tuple
                            [
                              Ty.path "argus_kernel::types::ConfLevel";
                              Ty.path "argus_kernel::types::EgressKind"
                            ];
                          Ty.path "argus_kernel::background::FlowMode";
                          Ty.path "alloc::alloc::Global"
                        ],
                      "get",
                      [],
                      [
                        Ty.tuple
                          [
                            Ty.path "argus_kernel::types::ConfLevel";
                            Ty.path "argus_kernel::types::EgressKind"
                          ]
                      ]
                    |),
                    [
                      M.borrow (|
                        Pointer.Kind.Ref,
                        M.SubPointer.get_struct_record_field (|
                          M.deref (| M.read (| self |) |),
                          "argus_kernel::background::BackgroundTheory",
                          "flow_policy"
                        |)
                      |);
                      M.borrow (|
                        Pointer.Kind.Ref,
                        M.deref (|
                          M.borrow (|
                            Pointer.Kind.Ref,
                            M.alloc (|
                              Ty.tuple
                                [
                                  Ty.path "argus_kernel::types::ConfLevel";
                                  Ty.path "argus_kernel::types::EgressKind"
                                ],
                              Value.Tuple [ M.read (| level |); M.read (| egress |) ]
                            |)
                          |)
                        |)
                      |)
                    ]
                  |)
                ]
              |);
              Value.StructTuple "argus_kernel::background::FlowMode::Deny" [] [] []
            ]
          |)))
      | _, _, _ => M.impossible "wrong number of arguments"
      end.
    
    Global Instance AssociatedFunction_flow_mode :
      M.IsAssociatedFunction.C Self "flow_mode" flow_mode.
    Admitted.
    Global Typeclasses Opaque flow_mode.
    
    (*
        pub fn has_flow_override(&self, agent: &AgentId, tool: &ToolId, level: ConfLevel) -> bool {
            self.flow_overrides
                .contains(&(agent.clone(), tool.clone(), level))
        }
    *)
    Definition has_flow_override (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
      match ε, τ, α with
      | [], [], [ self; agent; tool; level ] =>
        ltac:(M.monadic
          (let self :=
            M.alloc (|
              Ty.apply (Ty.path "&") [] [ Ty.path "argus_kernel::background::BackgroundTheory" ],
              self
            |) in
          let agent :=
            M.alloc (|
              Ty.apply (Ty.path "&") [] [ Ty.path "argus_kernel::types::AgentId" ],
              agent
            |) in
          let tool :=
            M.alloc (|
              Ty.apply (Ty.path "&") [] [ Ty.path "argus_kernel::types::ToolId" ],
              tool
            |) in
          let level := M.alloc (| Ty.path "argus_kernel::types::ConfLevel", level |) in
          M.call_closure (|
            Ty.path "bool",
            M.get_associated_function (|
              Ty.apply
                (Ty.path "alloc::collections::btree::set::BTreeSet")
                []
                [
                  Ty.tuple
                    [
                      Ty.path "argus_kernel::types::AgentId";
                      Ty.path "argus_kernel::types::ToolId";
                      Ty.path "argus_kernel::types::ConfLevel"
                    ];
                  Ty.path "alloc::alloc::Global"
                ],
              "contains",
              [],
              [
                Ty.tuple
                  [
                    Ty.path "argus_kernel::types::AgentId";
                    Ty.path "argus_kernel::types::ToolId";
                    Ty.path "argus_kernel::types::ConfLevel"
                  ]
              ]
            |),
            [
              M.borrow (|
                Pointer.Kind.Ref,
                M.SubPointer.get_struct_record_field (|
                  M.deref (| M.read (| self |) |),
                  "argus_kernel::background::BackgroundTheory",
                  "flow_overrides"
                |)
              |);
              M.borrow (|
                Pointer.Kind.Ref,
                M.deref (|
                  M.borrow (|
                    Pointer.Kind.Ref,
                    M.alloc (|
                      Ty.tuple
                        [
                          Ty.path "argus_kernel::types::AgentId";
                          Ty.path "argus_kernel::types::ToolId";
                          Ty.path "argus_kernel::types::ConfLevel"
                        ],
                      Value.Tuple
                        [
                          M.call_closure (|
                            Ty.path "argus_kernel::types::AgentId",
                            M.get_trait_method (|
                              "core::clone::Clone",
                              Ty.path "argus_kernel::types::AgentId",
                              [],
                              [],
                              "clone",
                              [],
                              []
                            |),
                            [ M.borrow (| Pointer.Kind.Ref, M.deref (| M.read (| agent |) |) |) ]
                          |);
                          M.call_closure (|
                            Ty.path "argus_kernel::types::ToolId",
                            M.get_trait_method (|
                              "core::clone::Clone",
                              Ty.path "argus_kernel::types::ToolId",
                              [],
                              [],
                              "clone",
                              [],
                              []
                            |),
                            [ M.borrow (| Pointer.Kind.Ref, M.deref (| M.read (| tool |) |) |) ]
                          |);
                          M.read (| level |)
                        ]
                    |)
                  |)
                |)
              |)
            ]
          |)))
      | _, _, _ => M.impossible "wrong number of arguments"
      end.
    
    Global Instance AssociatedFunction_has_flow_override :
      M.IsAssociatedFunction.C Self "has_flow_override" has_flow_override.
    Admitted.
    Global Typeclasses Opaque has_flow_override.
    
    (*
        pub fn registered_tools(&self) -> impl Iterator<Item = &ToolId> {
            self.tools.keys()
        }
    *)
    Definition registered_tools (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
      match ε, τ, α with
      | [], [], [ self ] =>
        ltac:(M.monadic
          (let self :=
            M.alloc (|
              Ty.apply (Ty.path "&") [] [ Ty.path "argus_kernel::background::BackgroundTheory" ],
              self
            |) in
          M.call_closure (|
            Ty.apply
              (Ty.path "alloc::collections::btree::map::Keys")
              []
              [
                Ty.path "argus_kernel::types::ToolId";
                Ty.path "argus_kernel::background::ToolMetadata"
              ],
            M.get_associated_function (|
              Ty.apply
                (Ty.path "alloc::collections::btree::map::BTreeMap")
                []
                [
                  Ty.path "argus_kernel::types::ToolId";
                  Ty.path "argus_kernel::background::ToolMetadata";
                  Ty.path "alloc::alloc::Global"
                ],
              "keys",
              [],
              []
            |),
            [
              M.borrow (|
                Pointer.Kind.Ref,
                M.SubPointer.get_struct_record_field (|
                  M.deref (| M.read (| self |) |),
                  "argus_kernel::background::BackgroundTheory",
                  "tools"
                |)
              |)
            ]
          |)))
      | _, _, _ => M.impossible "wrong number of arguments"
      end.
    
    Global Instance AssociatedFunction_registered_tools :
      M.IsAssociatedFunction.C Self "registered_tools" registered_tools.
    Admitted.
    Global Typeclasses Opaque registered_tools.
  End Impl_argus_kernel_background_BackgroundTheory.
  
  (* StructRecord
    {
      name := "BackgroundTheoryBuilder";
      const_params := [];
      ty_params := [];
      fields :=
        [
          ("tools",
            Ty.apply
              (Ty.path "alloc::collections::btree::map::BTreeMap")
              []
              [
                Ty.path "argus_kernel::types::ToolId";
                Ty.path "argus_kernel::background::ToolMetadata";
                Ty.path "alloc::alloc::Global"
              ]);
          ("flow_policy",
            Ty.apply
              (Ty.path "alloc::collections::btree::map::BTreeMap")
              []
              [
                Ty.tuple
                  [
                    Ty.path "argus_kernel::types::ConfLevel";
                    Ty.path "argus_kernel::types::EgressKind"
                  ];
                Ty.path "argus_kernel::background::FlowMode";
                Ty.path "alloc::alloc::Global"
              ]);
          ("flow_overrides",
            Ty.apply
              (Ty.path "alloc::collections::btree::set::BTreeSet")
              []
              [
                Ty.tuple
                  [
                    Ty.path "argus_kernel::types::AgentId";
                    Ty.path "argus_kernel::types::ToolId";
                    Ty.path "argus_kernel::types::ConfLevel"
                  ];
                Ty.path "alloc::alloc::Global"
              ])
        ];
    } *)
  
  Module Impl_argus_kernel_background_BackgroundTheoryBuilder.
    Definition Self : Ty.t := Ty.path "argus_kernel::background::BackgroundTheoryBuilder".
    
    (*
        pub fn new() -> Self {
            Self {
                tools: BTreeMap::new(),
                flow_policy: BTreeMap::new(),
                flow_overrides: BTreeSet::new(),
            }
        }
    *)
    Definition new (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
      match ε, τ, α with
      | [], [], [] =>
        ltac:(M.monadic
          (Value.mkStructRecord
            "argus_kernel::background::BackgroundTheoryBuilder"
            []
            []
            [
              ("tools",
                M.call_closure (|
                  Ty.apply
                    (Ty.path "alloc::collections::btree::map::BTreeMap")
                    []
                    [
                      Ty.path "argus_kernel::types::ToolId";
                      Ty.path "argus_kernel::background::ToolMetadata";
                      Ty.path "alloc::alloc::Global"
                    ],
                  M.get_associated_function (|
                    Ty.apply
                      (Ty.path "alloc::collections::btree::map::BTreeMap")
                      []
                      [
                        Ty.path "argus_kernel::types::ToolId";
                        Ty.path "argus_kernel::background::ToolMetadata";
                        Ty.path "alloc::alloc::Global"
                      ],
                    "new",
                    [],
                    []
                  |),
                  []
                |));
              ("flow_policy",
                M.call_closure (|
                  Ty.apply
                    (Ty.path "alloc::collections::btree::map::BTreeMap")
                    []
                    [
                      Ty.tuple
                        [
                          Ty.path "argus_kernel::types::ConfLevel";
                          Ty.path "argus_kernel::types::EgressKind"
                        ];
                      Ty.path "argus_kernel::background::FlowMode";
                      Ty.path "alloc::alloc::Global"
                    ],
                  M.get_associated_function (|
                    Ty.apply
                      (Ty.path "alloc::collections::btree::map::BTreeMap")
                      []
                      [
                        Ty.tuple
                          [
                            Ty.path "argus_kernel::types::ConfLevel";
                            Ty.path "argus_kernel::types::EgressKind"
                          ];
                        Ty.path "argus_kernel::background::FlowMode";
                        Ty.path "alloc::alloc::Global"
                      ],
                    "new",
                    [],
                    []
                  |),
                  []
                |));
              ("flow_overrides",
                M.call_closure (|
                  Ty.apply
                    (Ty.path "alloc::collections::btree::set::BTreeSet")
                    []
                    [
                      Ty.tuple
                        [
                          Ty.path "argus_kernel::types::AgentId";
                          Ty.path "argus_kernel::types::ToolId";
                          Ty.path "argus_kernel::types::ConfLevel"
                        ];
                      Ty.path "alloc::alloc::Global"
                    ],
                  M.get_associated_function (|
                    Ty.apply
                      (Ty.path "alloc::collections::btree::set::BTreeSet")
                      []
                      [
                        Ty.tuple
                          [
                            Ty.path "argus_kernel::types::AgentId";
                            Ty.path "argus_kernel::types::ToolId";
                            Ty.path "argus_kernel::types::ConfLevel"
                          ];
                        Ty.path "alloc::alloc::Global"
                      ],
                    "new",
                    [],
                    []
                  |),
                  []
                |))
            ]))
      | _, _, _ => M.impossible "wrong number of arguments"
      end.
    
    Global Instance AssociatedFunction_new : M.IsAssociatedFunction.C Self "new" new.
    Admitted.
    Global Typeclasses Opaque new.
    
    (*
        pub fn register_tool(&mut self, id: ToolId, metadata: ToolMetadata) -> &mut Self {
            self.tools.insert(id, metadata);
            self
        }
    *)
    Definition register_tool (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
      match ε, τ, α with
      | [], [], [ self; id; metadata ] =>
        ltac:(M.monadic
          (let self :=
            M.alloc (|
              Ty.apply
                (Ty.path "&mut")
                []
                [ Ty.path "argus_kernel::background::BackgroundTheoryBuilder" ],
              self
            |) in
          let id := M.alloc (| Ty.path "argus_kernel::types::ToolId", id |) in
          let metadata :=
            M.alloc (| Ty.path "argus_kernel::background::ToolMetadata", metadata |) in
          M.borrow (|
            Pointer.Kind.MutRef,
            M.deref (|
              M.read (|
                let~ _ :
                    Ty.apply
                      (Ty.path "core::option::Option")
                      []
                      [ Ty.path "argus_kernel::background::ToolMetadata" ] :=
                  M.call_closure (|
                    Ty.apply
                      (Ty.path "core::option::Option")
                      []
                      [ Ty.path "argus_kernel::background::ToolMetadata" ],
                    M.get_associated_function (|
                      Ty.apply
                        (Ty.path "alloc::collections::btree::map::BTreeMap")
                        []
                        [
                          Ty.path "argus_kernel::types::ToolId";
                          Ty.path "argus_kernel::background::ToolMetadata";
                          Ty.path "alloc::alloc::Global"
                        ],
                      "insert",
                      [],
                      []
                    |),
                    [
                      M.borrow (|
                        Pointer.Kind.MutRef,
                        M.SubPointer.get_struct_record_field (|
                          M.deref (| M.read (| self |) |),
                          "argus_kernel::background::BackgroundTheoryBuilder",
                          "tools"
                        |)
                      |);
                      M.read (| id |);
                      M.read (| metadata |)
                    ]
                  |) in
                M.alloc (|
                  Ty.apply
                    (Ty.path "&mut")
                    []
                    [ Ty.path "argus_kernel::background::BackgroundTheoryBuilder" ],
                  M.borrow (| Pointer.Kind.MutRef, M.deref (| M.read (| self |) |) |)
                |)
              |)
            |)
          |)))
      | _, _, _ => M.impossible "wrong number of arguments"
      end.
    
    Global Instance AssociatedFunction_register_tool :
      M.IsAssociatedFunction.C Self "register_tool" register_tool.
    Admitted.
    Global Typeclasses Opaque register_tool.
    
    (*
        pub fn set_flow(
            &mut self,
            level: ConfLevel,
            egress: EgressKind,
            mode: FlowMode,
        ) -> &mut Self {
            self.flow_policy.insert((level, egress), mode);
            self
        }
    *)
    Definition set_flow (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
      match ε, τ, α with
      | [], [], [ self; level; egress; mode ] =>
        ltac:(M.monadic
          (let self :=
            M.alloc (|
              Ty.apply
                (Ty.path "&mut")
                []
                [ Ty.path "argus_kernel::background::BackgroundTheoryBuilder" ],
              self
            |) in
          let level := M.alloc (| Ty.path "argus_kernel::types::ConfLevel", level |) in
          let egress := M.alloc (| Ty.path "argus_kernel::types::EgressKind", egress |) in
          let mode := M.alloc (| Ty.path "argus_kernel::background::FlowMode", mode |) in
          M.borrow (|
            Pointer.Kind.MutRef,
            M.deref (|
              M.read (|
                let~ _ :
                    Ty.apply
                      (Ty.path "core::option::Option")
                      []
                      [ Ty.path "argus_kernel::background::FlowMode" ] :=
                  M.call_closure (|
                    Ty.apply
                      (Ty.path "core::option::Option")
                      []
                      [ Ty.path "argus_kernel::background::FlowMode" ],
                    M.get_associated_function (|
                      Ty.apply
                        (Ty.path "alloc::collections::btree::map::BTreeMap")
                        []
                        [
                          Ty.tuple
                            [
                              Ty.path "argus_kernel::types::ConfLevel";
                              Ty.path "argus_kernel::types::EgressKind"
                            ];
                          Ty.path "argus_kernel::background::FlowMode";
                          Ty.path "alloc::alloc::Global"
                        ],
                      "insert",
                      [],
                      []
                    |),
                    [
                      M.borrow (|
                        Pointer.Kind.MutRef,
                        M.SubPointer.get_struct_record_field (|
                          M.deref (| M.read (| self |) |),
                          "argus_kernel::background::BackgroundTheoryBuilder",
                          "flow_policy"
                        |)
                      |);
                      Value.Tuple [ M.read (| level |); M.read (| egress |) ];
                      M.read (| mode |)
                    ]
                  |) in
                M.alloc (|
                  Ty.apply
                    (Ty.path "&mut")
                    []
                    [ Ty.path "argus_kernel::background::BackgroundTheoryBuilder" ],
                  M.borrow (| Pointer.Kind.MutRef, M.deref (| M.read (| self |) |) |)
                |)
              |)
            |)
          |)))
      | _, _, _ => M.impossible "wrong number of arguments"
      end.
    
    Global Instance AssociatedFunction_set_flow : M.IsAssociatedFunction.C Self "set_flow" set_flow.
    Admitted.
    Global Typeclasses Opaque set_flow.
    
    (*
        pub fn add_override(
            &mut self,
            agent: AgentId,
            tool: ToolId,
            level: ConfLevel,
        ) -> &mut Self {
            self.flow_overrides.insert((agent, tool, level));
            self
        }
    *)
    Definition add_override (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
      match ε, τ, α with
      | [], [], [ self; agent; tool; level ] =>
        ltac:(M.monadic
          (let self :=
            M.alloc (|
              Ty.apply
                (Ty.path "&mut")
                []
                [ Ty.path "argus_kernel::background::BackgroundTheoryBuilder" ],
              self
            |) in
          let agent := M.alloc (| Ty.path "argus_kernel::types::AgentId", agent |) in
          let tool := M.alloc (| Ty.path "argus_kernel::types::ToolId", tool |) in
          let level := M.alloc (| Ty.path "argus_kernel::types::ConfLevel", level |) in
          M.borrow (|
            Pointer.Kind.MutRef,
            M.deref (|
              M.read (|
                let~ _ : Ty.path "bool" :=
                  M.call_closure (|
                    Ty.path "bool",
                    M.get_associated_function (|
                      Ty.apply
                        (Ty.path "alloc::collections::btree::set::BTreeSet")
                        []
                        [
                          Ty.tuple
                            [
                              Ty.path "argus_kernel::types::AgentId";
                              Ty.path "argus_kernel::types::ToolId";
                              Ty.path "argus_kernel::types::ConfLevel"
                            ];
                          Ty.path "alloc::alloc::Global"
                        ],
                      "insert",
                      [],
                      []
                    |),
                    [
                      M.borrow (|
                        Pointer.Kind.MutRef,
                        M.SubPointer.get_struct_record_field (|
                          M.deref (| M.read (| self |) |),
                          "argus_kernel::background::BackgroundTheoryBuilder",
                          "flow_overrides"
                        |)
                      |);
                      Value.Tuple [ M.read (| agent |); M.read (| tool |); M.read (| level |) ]
                    ]
                  |) in
                M.alloc (|
                  Ty.apply
                    (Ty.path "&mut")
                    []
                    [ Ty.path "argus_kernel::background::BackgroundTheoryBuilder" ],
                  M.borrow (| Pointer.Kind.MutRef, M.deref (| M.read (| self |) |) |)
                |)
              |)
            |)
          |)))
      | _, _, _ => M.impossible "wrong number of arguments"
      end.
    
    Global Instance AssociatedFunction_add_override :
      M.IsAssociatedFunction.C Self "add_override" add_override.
    Admitted.
    Global Typeclasses Opaque add_override.
    
    (*
        pub fn build(self) -> BackgroundTheory {
            BackgroundTheory {
                tools: self.tools,
                flow_policy: self.flow_policy,
                flow_overrides: self.flow_overrides,
            }
        }
    *)
    Definition build (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
      match ε, τ, α with
      | [], [], [ self ] =>
        ltac:(M.monadic
          (let self :=
            M.alloc (| Ty.path "argus_kernel::background::BackgroundTheoryBuilder", self |) in
          Value.mkStructRecord
            "argus_kernel::background::BackgroundTheory"
            []
            []
            [
              ("tools",
                M.read (|
                  M.SubPointer.get_struct_record_field (|
                    self,
                    "argus_kernel::background::BackgroundTheoryBuilder",
                    "tools"
                  |)
                |));
              ("flow_policy",
                M.read (|
                  M.SubPointer.get_struct_record_field (|
                    self,
                    "argus_kernel::background::BackgroundTheoryBuilder",
                    "flow_policy"
                  |)
                |));
              ("flow_overrides",
                M.read (|
                  M.SubPointer.get_struct_record_field (|
                    self,
                    "argus_kernel::background::BackgroundTheoryBuilder",
                    "flow_overrides"
                  |)
                |))
            ]))
      | _, _, _ => M.impossible "wrong number of arguments"
      end.
    
    Global Instance AssociatedFunction_build : M.IsAssociatedFunction.C Self "build" build.
    Admitted.
    Global Typeclasses Opaque build.
  End Impl_argus_kernel_background_BackgroundTheoryBuilder.
  
  Module Impl_core_default_Default_for_argus_kernel_background_BackgroundTheoryBuilder.
    Definition Self : Ty.t := Ty.path "argus_kernel::background::BackgroundTheoryBuilder".
    
    (*
        fn default() -> Self {
            Self::new()
        }
    *)
    Definition default (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
      match ε, τ, α with
      | [], [], [] =>
        ltac:(M.monadic
          (M.call_closure (|
            Ty.path "argus_kernel::background::BackgroundTheoryBuilder",
            M.get_associated_function (|
              Ty.path "argus_kernel::background::BackgroundTheoryBuilder",
              "new",
              [],
              []
            |),
            []
          |)))
      | _, _, _ => M.impossible "wrong number of arguments"
      end.
    
    Axiom Implements :
      M.IsTraitInstance
        "core::default::Default"
        (* Trait polymorphic consts *) []
        (* Trait polymorphic types *) []
        Self
        (* Instance *) [ ("default", InstanceField.Method default) ].
  End Impl_core_default_Default_for_argus_kernel_background_BackgroundTheoryBuilder.
End background.
