(* Generated by rocq-of-rust *)
Require Import RocqOfRust.RocqOfRust.

Module error.
  (*
  Enum KernelError
  {
    const_params := [];
    ty_params := [];
    variants :=
      [
        {
          name := "PreconditionViolation";
          item := StructTuple [ Ty.path "alloc::string::String" ];
        };
        {
          name := "EventStoreError";
          item := StructTuple [ Ty.path "alloc::string::String" ];
        }
      ];
  }
  *)
  
  Axiom IsDiscriminant_KernelError_PreconditionViolation :
    M.IsDiscriminant "argus_kernel::error::KernelError::PreconditionViolation" 0.
  Axiom IsDiscriminant_KernelError_EventStoreError :
    M.IsDiscriminant "argus_kernel::error::KernelError::EventStoreError" 1.
  
  Module Impl_core_fmt_Debug_for_argus_kernel_error_KernelError.
    Definition Self : Ty.t := Ty.path "argus_kernel::error::KernelError".
    
    (* Debug *)
    Definition fmt (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
      match ε, τ, α with
      | [], [], [ self; f ] =>
        ltac:(M.monadic
          (let self :=
            M.alloc (|
              Ty.apply (Ty.path "&") [] [ Ty.path "argus_kernel::error::KernelError" ],
              self
            |) in
          let f :=
            M.alloc (| Ty.apply (Ty.path "&mut") [] [ Ty.path "core::fmt::Formatter" ], f |) in
          M.match_operator (|
            Ty.apply
              (Ty.path "core::result::Result")
              []
              [ Ty.tuple []; Ty.path "core::fmt::Error" ],
            self,
            [
              fun γ =>
                ltac:(M.monadic
                  (let γ := M.deref (| M.read (| γ |) |) in
                  let γ1_0 :=
                    M.SubPointer.get_struct_tuple_field (|
                      γ,
                      "argus_kernel::error::KernelError::PreconditionViolation",
                      0
                    |) in
                  let __self_0 :=
                    M.alloc (|
                      Ty.apply (Ty.path "&") [] [ Ty.path "alloc::string::String" ],
                      γ1_0
                    |) in
                  M.call_closure (|
                    Ty.apply
                      (Ty.path "core::result::Result")
                      []
                      [ Ty.tuple []; Ty.path "core::fmt::Error" ],
                    M.get_associated_function (|
                      Ty.path "core::fmt::Formatter",
                      "debug_tuple_field1_finish",
                      [],
                      []
                    |),
                    [
                      M.borrow (| Pointer.Kind.MutRef, M.deref (| M.read (| f |) |) |);
                      M.borrow (|
                        Pointer.Kind.Ref,
                        M.deref (| mk_str (| "PreconditionViolation" |) |)
                      |);
                      M.call_closure (|
                        Ty.apply (Ty.path "&") [] [ Ty.dyn [ ("core::fmt::Debug::Trait", []) ] ],
                        M.pointer_coercion
                          M.PointerCoercion.Unsize
                          (Ty.apply
                            (Ty.path "&")
                            []
                            [ Ty.apply (Ty.path "&") [] [ Ty.path "alloc::string::String" ] ])
                          (Ty.apply
                            (Ty.path "&")
                            []
                            [ Ty.dyn [ ("core::fmt::Debug::Trait", []) ] ]),
                        [
                          M.borrow (|
                            Pointer.Kind.Ref,
                            M.deref (| M.borrow (| Pointer.Kind.Ref, __self_0 |) |)
                          |)
                        ]
                      |)
                    ]
                  |)));
              fun γ =>
                ltac:(M.monadic
                  (let γ := M.deref (| M.read (| γ |) |) in
                  let γ1_0 :=
                    M.SubPointer.get_struct_tuple_field (|
                      γ,
                      "argus_kernel::error::KernelError::EventStoreError",
                      0
                    |) in
                  let __self_0 :=
                    M.alloc (|
                      Ty.apply (Ty.path "&") [] [ Ty.path "alloc::string::String" ],
                      γ1_0
                    |) in
                  M.call_closure (|
                    Ty.apply
                      (Ty.path "core::result::Result")
                      []
                      [ Ty.tuple []; Ty.path "core::fmt::Error" ],
                    M.get_associated_function (|
                      Ty.path "core::fmt::Formatter",
                      "debug_tuple_field1_finish",
                      [],
                      []
                    |),
                    [
                      M.borrow (| Pointer.Kind.MutRef, M.deref (| M.read (| f |) |) |);
                      M.borrow (| Pointer.Kind.Ref, M.deref (| mk_str (| "EventStoreError" |) |) |);
                      M.call_closure (|
                        Ty.apply (Ty.path "&") [] [ Ty.dyn [ ("core::fmt::Debug::Trait", []) ] ],
                        M.pointer_coercion
                          M.PointerCoercion.Unsize
                          (Ty.apply
                            (Ty.path "&")
                            []
                            [ Ty.apply (Ty.path "&") [] [ Ty.path "alloc::string::String" ] ])
                          (Ty.apply
                            (Ty.path "&")
                            []
                            [ Ty.dyn [ ("core::fmt::Debug::Trait", []) ] ]),
                        [
                          M.borrow (|
                            Pointer.Kind.Ref,
                            M.deref (| M.borrow (| Pointer.Kind.Ref, __self_0 |) |)
                          |)
                        ]
                      |)
                    ]
                  |)))
            ]
          |)))
      | _, _, _ => M.impossible "wrong number of arguments"
      end.
    
    Axiom Implements :
      M.IsTraitInstance
        "core::fmt::Debug"
        (* Trait polymorphic consts *) []
        (* Trait polymorphic types *) []
        Self
        (* Instance *) [ ("fmt", InstanceField.Method fmt) ].
  End Impl_core_fmt_Debug_for_argus_kernel_error_KernelError.
  
  Module Impl_core_error_Error_for_argus_kernel_error_KernelError.
    Definition Self : Ty.t := Ty.path "argus_kernel::error::KernelError".
    
    Axiom Implements :
      M.IsTraitInstance
        "core::error::Error"
        (* Trait polymorphic consts *) []
        (* Trait polymorphic types *) []
        Self
        (* Instance *) [].
  End Impl_core_error_Error_for_argus_kernel_error_KernelError.
  
  Module Impl_core_fmt_Display_for_argus_kernel_error_KernelError.
    Definition Self : Ty.t := Ty.path "argus_kernel::error::KernelError".
    
    (* thiserror::Error *)
    Definition fmt (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
      match ε, τ, α with
      | [], [], [ self; __formatter ] =>
        ltac:(M.monadic
          (let self :=
            M.alloc (|
              Ty.apply (Ty.path "&") [] [ Ty.path "argus_kernel::error::KernelError" ],
              self
            |) in
          let __formatter :=
            M.alloc (|
              Ty.apply (Ty.path "&mut") [] [ Ty.path "core::fmt::Formatter" ],
              __formatter
            |) in
          M.match_operator (|
            Ty.apply
              (Ty.path "core::result::Result")
              []
              [ Ty.tuple []; Ty.path "core::fmt::Error" ],
            self,
            [
              fun γ =>
                ltac:(M.monadic
                  (let γ := M.deref (| M.read (| γ |) |) in
                  let γ1_0 :=
                    M.SubPointer.get_struct_tuple_field (|
                      γ,
                      "argus_kernel::error::KernelError::PreconditionViolation",
                      0
                    |) in
                  let _0 :=
                    M.alloc (|
                      Ty.apply (Ty.path "&") [] [ Ty.path "alloc::string::String" ],
                      γ1_0
                    |) in
                  M.match_operator (|
                    Ty.apply
                      (Ty.path "core::result::Result")
                      []
                      [ Ty.tuple []; Ty.path "core::fmt::Error" ],
                    M.alloc (|
                      Ty.tuple [ Ty.apply (Ty.path "&") [] [ Ty.path "alloc::string::String" ] ],
                      Value.Tuple
                        [
                          M.call_closure (|
                            Ty.apply (Ty.path "&") [] [ Ty.path "alloc::string::String" ],
                            M.get_trait_method (|
                              "thiserror::display::AsDisplay",
                              Ty.apply (Ty.path "&") [] [ Ty.path "alloc::string::String" ],
                              [],
                              [],
                              "as_display",
                              [],
                              []
                            |),
                            [ M.borrow (| Pointer.Kind.Ref, _0 |) ]
                          |)
                        ]
                    |),
                    [
                      fun γ =>
                        ltac:(M.monadic
                          (let γ0_0 := M.SubPointer.get_tuple_field (| γ, 0 |) in
                          let __display0 :=
                            M.copy (|
                              Ty.apply (Ty.path "&") [] [ Ty.path "alloc::string::String" ],
                              γ0_0
                            |) in
                          M.call_closure (|
                            Ty.apply
                              (Ty.path "core::result::Result")
                              []
                              [ Ty.tuple []; Ty.path "core::fmt::Error" ],
                            M.get_associated_function (|
                              Ty.path "core::fmt::Formatter",
                              "write_fmt",
                              [],
                              []
                            |),
                            [
                              M.borrow (|
                                Pointer.Kind.MutRef,
                                M.deref (| M.read (| __formatter |) |)
                              |);
                              M.call_closure (|
                                Ty.path "core::fmt::Arguments",
                                M.get_associated_function (|
                                  Ty.path "core::fmt::Arguments",
                                  "new_v1",
                                  [
                                    Value.Integer IntegerKind.Usize 1;
                                    Value.Integer IntegerKind.Usize 1
                                  ],
                                  []
                                |),
                                [
                                  M.borrow (|
                                    Pointer.Kind.Ref,
                                    M.deref (|
                                      M.borrow (|
                                        Pointer.Kind.Ref,
                                        M.alloc (|
                                          Ty.apply
                                            (Ty.path "array")
                                            [ Value.Integer IntegerKind.Usize 1 ]
                                            [ Ty.apply (Ty.path "&") [] [ Ty.path "str" ] ],
                                          Value.Array [ mk_str (| "precondition violated: " |) ]
                                        |)
                                      |)
                                    |)
                                  |);
                                  M.borrow (|
                                    Pointer.Kind.Ref,
                                    M.deref (|
                                      M.borrow (|
                                        Pointer.Kind.Ref,
                                        M.alloc (|
                                          Ty.apply
                                            (Ty.path "array")
                                            [ Value.Integer IntegerKind.Usize 1 ]
                                            [ Ty.path "core::fmt::rt::Argument" ],
                                          Value.Array
                                            [
                                              M.call_closure (|
                                                Ty.path "core::fmt::rt::Argument",
                                                M.get_associated_function (|
                                                  Ty.path "core::fmt::rt::Argument",
                                                  "new_display",
                                                  [],
                                                  [
                                                    Ty.apply
                                                      (Ty.path "&")
                                                      []
                                                      [ Ty.path "alloc::string::String" ]
                                                  ]
                                                |),
                                                [
                                                  M.borrow (|
                                                    Pointer.Kind.Ref,
                                                    M.deref (|
                                                      M.borrow (| Pointer.Kind.Ref, __display0 |)
                                                    |)
                                                  |)
                                                ]
                                              |)
                                            ]
                                        |)
                                      |)
                                    |)
                                  |)
                                ]
                              |)
                            ]
                          |)))
                    ]
                  |)));
              fun γ =>
                ltac:(M.monadic
                  (let γ := M.deref (| M.read (| γ |) |) in
                  let γ1_0 :=
                    M.SubPointer.get_struct_tuple_field (|
                      γ,
                      "argus_kernel::error::KernelError::EventStoreError",
                      0
                    |) in
                  let _0 :=
                    M.alloc (|
                      Ty.apply (Ty.path "&") [] [ Ty.path "alloc::string::String" ],
                      γ1_0
                    |) in
                  M.match_operator (|
                    Ty.apply
                      (Ty.path "core::result::Result")
                      []
                      [ Ty.tuple []; Ty.path "core::fmt::Error" ],
                    M.alloc (|
                      Ty.tuple [ Ty.apply (Ty.path "&") [] [ Ty.path "alloc::string::String" ] ],
                      Value.Tuple
                        [
                          M.call_closure (|
                            Ty.apply (Ty.path "&") [] [ Ty.path "alloc::string::String" ],
                            M.get_trait_method (|
                              "thiserror::display::AsDisplay",
                              Ty.apply (Ty.path "&") [] [ Ty.path "alloc::string::String" ],
                              [],
                              [],
                              "as_display",
                              [],
                              []
                            |),
                            [ M.borrow (| Pointer.Kind.Ref, _0 |) ]
                          |)
                        ]
                    |),
                    [
                      fun γ =>
                        ltac:(M.monadic
                          (let γ0_0 := M.SubPointer.get_tuple_field (| γ, 0 |) in
                          let __display0 :=
                            M.copy (|
                              Ty.apply (Ty.path "&") [] [ Ty.path "alloc::string::String" ],
                              γ0_0
                            |) in
                          M.call_closure (|
                            Ty.apply
                              (Ty.path "core::result::Result")
                              []
                              [ Ty.tuple []; Ty.path "core::fmt::Error" ],
                            M.get_associated_function (|
                              Ty.path "core::fmt::Formatter",
                              "write_fmt",
                              [],
                              []
                            |),
                            [
                              M.borrow (|
                                Pointer.Kind.MutRef,
                                M.deref (| M.read (| __formatter |) |)
                              |);
                              M.call_closure (|
                                Ty.path "core::fmt::Arguments",
                                M.get_associated_function (|
                                  Ty.path "core::fmt::Arguments",
                                  "new_v1",
                                  [
                                    Value.Integer IntegerKind.Usize 1;
                                    Value.Integer IntegerKind.Usize 1
                                  ],
                                  []
                                |),
                                [
                                  M.borrow (|
                                    Pointer.Kind.Ref,
                                    M.deref (|
                                      M.borrow (|
                                        Pointer.Kind.Ref,
                                        M.alloc (|
                                          Ty.apply
                                            (Ty.path "array")
                                            [ Value.Integer IntegerKind.Usize 1 ]
                                            [ Ty.apply (Ty.path "&") [] [ Ty.path "str" ] ],
                                          Value.Array [ mk_str (| "event store error: " |) ]
                                        |)
                                      |)
                                    |)
                                  |);
                                  M.borrow (|
                                    Pointer.Kind.Ref,
                                    M.deref (|
                                      M.borrow (|
                                        Pointer.Kind.Ref,
                                        M.alloc (|
                                          Ty.apply
                                            (Ty.path "array")
                                            [ Value.Integer IntegerKind.Usize 1 ]
                                            [ Ty.path "core::fmt::rt::Argument" ],
                                          Value.Array
                                            [
                                              M.call_closure (|
                                                Ty.path "core::fmt::rt::Argument",
                                                M.get_associated_function (|
                                                  Ty.path "core::fmt::rt::Argument",
                                                  "new_display",
                                                  [],
                                                  [
                                                    Ty.apply
                                                      (Ty.path "&")
                                                      []
                                                      [ Ty.path "alloc::string::String" ]
                                                  ]
                                                |),
                                                [
                                                  M.borrow (|
                                                    Pointer.Kind.Ref,
                                                    M.deref (|
                                                      M.borrow (| Pointer.Kind.Ref, __display0 |)
                                                    |)
                                                  |)
                                                ]
                                              |)
                                            ]
                                        |)
                                      |)
                                    |)
                                  |)
                                ]
                              |)
                            ]
                          |)))
                    ]
                  |)))
            ]
          |)))
      | _, _, _ => M.impossible "wrong number of arguments"
      end.
    
    Axiom Implements :
      M.IsTraitInstance
        "core::fmt::Display"
        (* Trait polymorphic consts *) []
        (* Trait polymorphic types *) []
        Self
        (* Instance *) [ ("fmt", InstanceField.Method fmt) ].
  End Impl_core_fmt_Display_for_argus_kernel_error_KernelError.
End error.
