(* Generated by rocq-of-rust *)
Require Import RocqOfRust.RocqOfRust.

Module kernel.
  (* StructRecord
    {
      name := "Kernel";
      const_params := [];
      ty_params := [ "A"; "C"; "E" ];
      fields :=
        [
          ("state", Ty.path "argus_kernel::state::KernelState");
          ("background", Ty.path "argus_kernel::background::BackgroundTheory");
          ("sequence", Ty.path "u64");
          ("authorizer", A);
          ("content_gate", C);
          ("events", E)
        ];
    } *)
  
  Module Impl_argus_kernel_kernel_Kernel_A_C_E.
    Definition Self (A C E : Ty.t) : Ty.t :=
      Ty.apply (Ty.path "argus_kernel::kernel::Kernel") [] [ A; C; E ].
    
    (*
        pub fn new(
            background: BackgroundTheory,
            authorizer: A,
            content_gate: C,
            events: E,
        ) -> Self {
            Self {
                state: KernelState::initial(),
                background,
                sequence: 0,
                authorizer,
                content_gate,
                events,
            }
        }
    *)
    Definition new (A C E : Ty.t) (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
      let Self : Ty.t := Self A C E in
      match ε, τ, α with
      | [], [], [ background; authorizer; content_gate; events ] =>
        ltac:(M.monadic
          (let background :=
            M.alloc (| Ty.path "argus_kernel::background::BackgroundTheory", background |) in
          let authorizer := M.alloc (| A, authorizer |) in
          let content_gate := M.alloc (| C, content_gate |) in
          let events := M.alloc (| E, events |) in
          Value.mkStructRecord
            "argus_kernel::kernel::Kernel"
            []
            [ A; C; E ]
            [
              ("state",
                M.call_closure (|
                  Ty.path "argus_kernel::state::KernelState",
                  M.get_associated_function (|
                    Ty.path "argus_kernel::state::KernelState",
                    "initial",
                    [],
                    []
                  |),
                  []
                |));
              ("background", M.read (| background |));
              ("sequence", Value.Integer IntegerKind.U64 0);
              ("authorizer", M.read (| authorizer |));
              ("content_gate", M.read (| content_gate |));
              ("events", M.read (| events |))
            ]))
      | _, _, _ => M.impossible "wrong number of arguments"
      end.
    
    Global Instance AssociatedFunction_new :
      forall (A C E : Ty.t),
      M.IsAssociatedFunction.C (Self A C E) "new" (new A C E).
    Admitted.
    Global Typeclasses Opaque new.
    
    (*
        pub fn state(&self) -> &KernelState {
            &self.state
        }
    *)
    Definition state (A C E : Ty.t) (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
      let Self : Ty.t := Self A C E in
      match ε, τ, α with
      | [], [], [ self ] =>
        ltac:(M.monadic
          (let self :=
            M.alloc (|
              Ty.apply
                (Ty.path "&")
                []
                [ Ty.apply (Ty.path "argus_kernel::kernel::Kernel") [] [ A; C; E ] ],
              self
            |) in
          M.borrow (|
            Pointer.Kind.Ref,
            M.deref (|
              M.borrow (|
                Pointer.Kind.Ref,
                M.SubPointer.get_struct_record_field (|
                  M.deref (| M.read (| self |) |),
                  "argus_kernel::kernel::Kernel",
                  "state"
                |)
              |)
            |)
          |)))
      | _, _, _ => M.impossible "wrong number of arguments"
      end.
    
    Global Instance AssociatedFunction_state :
      forall (A C E : Ty.t),
      M.IsAssociatedFunction.C (Self A C E) "state" (state A C E).
    Admitted.
    Global Typeclasses Opaque state.
    
    (*
        pub fn background(&self) -> &BackgroundTheory {
            &self.background
        }
    *)
    Definition background
        (A C E : Ty.t)
        (ε : list Value.t)
        (τ : list Ty.t)
        (α : list Value.t)
        : M :=
      let Self : Ty.t := Self A C E in
      match ε, τ, α with
      | [], [], [ self ] =>
        ltac:(M.monadic
          (let self :=
            M.alloc (|
              Ty.apply
                (Ty.path "&")
                []
                [ Ty.apply (Ty.path "argus_kernel::kernel::Kernel") [] [ A; C; E ] ],
              self
            |) in
          M.borrow (|
            Pointer.Kind.Ref,
            M.deref (|
              M.borrow (|
                Pointer.Kind.Ref,
                M.SubPointer.get_struct_record_field (|
                  M.deref (| M.read (| self |) |),
                  "argus_kernel::kernel::Kernel",
                  "background"
                |)
              |)
            |)
          |)))
      | _, _, _ => M.impossible "wrong number of arguments"
      end.
    
    Global Instance AssociatedFunction_background :
      forall (A C E : Ty.t),
      M.IsAssociatedFunction.C (Self A C E) "background" (background A C E).
    Admitted.
    Global Typeclasses Opaque background.
    
    (*
        pub fn sequence(&self) -> u64 {
            self.sequence
        }
    *)
    Definition sequence (A C E : Ty.t) (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
      let Self : Ty.t := Self A C E in
      match ε, τ, α with
      | [], [], [ self ] =>
        ltac:(M.monadic
          (let self :=
            M.alloc (|
              Ty.apply
                (Ty.path "&")
                []
                [ Ty.apply (Ty.path "argus_kernel::kernel::Kernel") [] [ A; C; E ] ],
              self
            |) in
          M.read (|
            M.SubPointer.get_struct_record_field (|
              M.deref (| M.read (| self |) |),
              "argus_kernel::kernel::Kernel",
              "sequence"
            |)
          |)))
      | _, _, _ => M.impossible "wrong number of arguments"
      end.
    
    Global Instance AssociatedFunction_sequence :
      forall (A C E : Ty.t),
      M.IsAssociatedFunction.C (Self A C E) "sequence" (sequence A C E).
    Admitted.
    Global Typeclasses Opaque sequence.
    
    (*
        fn apply(
            &mut self,
            result: Result<(KernelState, KernelAction), KernelError>,
        ) -> Result<KernelEvent, KernelError> {
            let (new_state, action) = result?;
            let next_seq = self.sequence + 1;
            let event = KernelEvent::new(next_seq, action);
            self.events.append(&event)?;
            self.sequence = next_seq;
            self.state = new_state;
            Ok(event)
        }
    *)
    Definition apply (A C E : Ty.t) (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
      let Self : Ty.t := Self A C E in
      match ε, τ, α with
      | [], [], [ self; result ] =>
        ltac:(M.monadic
          (let self :=
            M.alloc (|
              Ty.apply
                (Ty.path "&mut")
                []
                [ Ty.apply (Ty.path "argus_kernel::kernel::Kernel") [] [ A; C; E ] ],
              self
            |) in
          let result :=
            M.alloc (|
              Ty.apply
                (Ty.path "core::result::Result")
                []
                [
                  Ty.tuple
                    [
                      Ty.path "argus_kernel::state::KernelState";
                      Ty.path "argus_kernel::event::KernelAction"
                    ];
                  Ty.path "argus_kernel::error::KernelError"
                ],
              result
            |) in
          M.catch_return
            (Ty.apply
              (Ty.path "core::result::Result")
              []
              [
                Ty.path "argus_kernel::event::KernelEvent";
                Ty.path "argus_kernel::error::KernelError"
              ]) (|
            ltac:(M.monadic
              (M.match_operator (|
                Ty.apply
                  (Ty.path "core::result::Result")
                  []
                  [
                    Ty.path "argus_kernel::event::KernelEvent";
                    Ty.path "argus_kernel::error::KernelError"
                  ],
                M.alloc (|
                  Ty.tuple
                    [
                      Ty.path "argus_kernel::state::KernelState";
                      Ty.path "argus_kernel::event::KernelAction"
                    ],
                  M.match_operator (|
                    Ty.tuple
                      [
                        Ty.path "argus_kernel::state::KernelState";
                        Ty.path "argus_kernel::event::KernelAction"
                      ],
                    M.alloc (|
                      Ty.apply
                        (Ty.path "core::ops::control_flow::ControlFlow")
                        []
                        [
                          Ty.apply
                            (Ty.path "core::result::Result")
                            []
                            [
                              Ty.path "core::convert::Infallible";
                              Ty.path "argus_kernel::error::KernelError"
                            ];
                          Ty.tuple
                            [
                              Ty.path "argus_kernel::state::KernelState";
                              Ty.path "argus_kernel::event::KernelAction"
                            ]
                        ],
                      M.call_closure (|
                        Ty.apply
                          (Ty.path "core::ops::control_flow::ControlFlow")
                          []
                          [
                            Ty.apply
                              (Ty.path "core::result::Result")
                              []
                              [
                                Ty.path "core::convert::Infallible";
                                Ty.path "argus_kernel::error::KernelError"
                              ];
                            Ty.tuple
                              [
                                Ty.path "argus_kernel::state::KernelState";
                                Ty.path "argus_kernel::event::KernelAction"
                              ]
                          ],
                        M.get_trait_method (|
                          "core::ops::try_trait::Try",
                          Ty.apply
                            (Ty.path "core::result::Result")
                            []
                            [
                              Ty.tuple
                                [
                                  Ty.path "argus_kernel::state::KernelState";
                                  Ty.path "argus_kernel::event::KernelAction"
                                ];
                              Ty.path "argus_kernel::error::KernelError"
                            ],
                          [],
                          [],
                          "branch",
                          [],
                          []
                        |),
                        [ M.read (| result |) ]
                      |)
                    |),
                    [
                      fun γ =>
                        ltac:(M.monadic
                          (let γ0_0 :=
                            M.SubPointer.get_struct_tuple_field (|
                              γ,
                              "core::ops::control_flow::ControlFlow::Break",
                              0
                            |) in
                          let residual :=
                            M.copy (|
                              Ty.apply
                                (Ty.path "core::result::Result")
                                []
                                [
                                  Ty.path "core::convert::Infallible";
                                  Ty.path "argus_kernel::error::KernelError"
                                ],
                              γ0_0
                            |) in
                          M.never_to_any (|
                            M.read (|
                              M.return_ (|
                                M.call_closure (|
                                  Ty.apply
                                    (Ty.path "core::result::Result")
                                    []
                                    [
                                      Ty.path "argus_kernel::event::KernelEvent";
                                      Ty.path "argus_kernel::error::KernelError"
                                    ],
                                  M.get_trait_method (|
                                    "core::ops::try_trait::FromResidual",
                                    Ty.apply
                                      (Ty.path "core::result::Result")
                                      []
                                      [
                                        Ty.path "argus_kernel::event::KernelEvent";
                                        Ty.path "argus_kernel::error::KernelError"
                                      ],
                                    [],
                                    [
                                      Ty.apply
                                        (Ty.path "core::result::Result")
                                        []
                                        [
                                          Ty.path "core::convert::Infallible";
                                          Ty.path "argus_kernel::error::KernelError"
                                        ]
                                    ],
                                    "from_residual",
                                    [],
                                    []
                                  |),
                                  [ M.read (| residual |) ]
                                |)
                              |)
                            |)
                          |)));
                      fun γ =>
                        ltac:(M.monadic
                          (let γ0_0 :=
                            M.SubPointer.get_struct_tuple_field (|
                              γ,
                              "core::ops::control_flow::ControlFlow::Continue",
                              0
                            |) in
                          let val :=
                            M.copy (|
                              Ty.tuple
                                [
                                  Ty.path "argus_kernel::state::KernelState";
                                  Ty.path "argus_kernel::event::KernelAction"
                                ],
                              γ0_0
                            |) in
                          M.read (| val |)))
                    ]
                  |)
                |),
                [
                  fun γ =>
                    ltac:(M.monadic
                      (let γ0_0 := M.SubPointer.get_tuple_field (| γ, 0 |) in
                      let γ0_1 := M.SubPointer.get_tuple_field (| γ, 1 |) in
                      let new_state :=
                        M.copy (| Ty.path "argus_kernel::state::KernelState", γ0_0 |) in
                      let action :=
                        M.copy (| Ty.path "argus_kernel::event::KernelAction", γ0_1 |) in
                      M.read (|
                        let~ next_seq : Ty.path "u64" :=
                          M.call_closure (|
                            Ty.path "u64",
                            BinOp.Wrap.add,
                            [
                              M.read (|
                                M.SubPointer.get_struct_record_field (|
                                  M.deref (| M.read (| self |) |),
                                  "argus_kernel::kernel::Kernel",
                                  "sequence"
                                |)
                              |);
                              Value.Integer IntegerKind.U64 1
                            ]
                          |) in
                        let~ event : Ty.path "argus_kernel::event::KernelEvent" :=
                          M.call_closure (|
                            Ty.path "argus_kernel::event::KernelEvent",
                            M.get_associated_function (|
                              Ty.path "argus_kernel::event::KernelEvent",
                              "new",
                              [],
                              []
                            |),
                            [ M.read (| next_seq |); M.read (| action |) ]
                          |) in
                        let~ _ : Ty.tuple [] :=
                          M.match_operator (|
                            Ty.tuple [],
                            M.alloc (|
                              Ty.apply
                                (Ty.path "core::ops::control_flow::ControlFlow")
                                []
                                [
                                  Ty.apply
                                    (Ty.path "core::result::Result")
                                    []
                                    [
                                      Ty.path "core::convert::Infallible";
                                      Ty.path "argus_kernel::error::KernelError"
                                    ];
                                  Ty.tuple []
                                ],
                              M.call_closure (|
                                Ty.apply
                                  (Ty.path "core::ops::control_flow::ControlFlow")
                                  []
                                  [
                                    Ty.apply
                                      (Ty.path "core::result::Result")
                                      []
                                      [
                                        Ty.path "core::convert::Infallible";
                                        Ty.path "argus_kernel::error::KernelError"
                                      ];
                                    Ty.tuple []
                                  ],
                                M.get_trait_method (|
                                  "core::ops::try_trait::Try",
                                  Ty.apply
                                    (Ty.path "core::result::Result")
                                    []
                                    [ Ty.tuple []; Ty.path "argus_kernel::error::KernelError" ],
                                  [],
                                  [],
                                  "branch",
                                  [],
                                  []
                                |),
                                [
                                  M.call_closure (|
                                    Ty.apply
                                      (Ty.path "core::result::Result")
                                      []
                                      [ Ty.tuple []; Ty.path "argus_kernel::error::KernelError" ],
                                    M.get_trait_method (|
                                      "argus_kernel::traits::EventStore",
                                      E,
                                      [],
                                      [],
                                      "append",
                                      [],
                                      []
                                    |),
                                    [
                                      M.borrow (|
                                        Pointer.Kind.Ref,
                                        M.SubPointer.get_struct_record_field (|
                                          M.deref (| M.read (| self |) |),
                                          "argus_kernel::kernel::Kernel",
                                          "events"
                                        |)
                                      |);
                                      M.borrow (|
                                        Pointer.Kind.Ref,
                                        M.deref (| M.borrow (| Pointer.Kind.Ref, event |) |)
                                      |)
                                    ]
                                  |)
                                ]
                              |)
                            |),
                            [
                              fun γ =>
                                ltac:(M.monadic
                                  (let γ0_0 :=
                                    M.SubPointer.get_struct_tuple_field (|
                                      γ,
                                      "core::ops::control_flow::ControlFlow::Break",
                                      0
                                    |) in
                                  let residual :=
                                    M.copy (|
                                      Ty.apply
                                        (Ty.path "core::result::Result")
                                        []
                                        [
                                          Ty.path "core::convert::Infallible";
                                          Ty.path "argus_kernel::error::KernelError"
                                        ],
                                      γ0_0
                                    |) in
                                  M.never_to_any (|
                                    M.read (|
                                      M.return_ (|
                                        M.call_closure (|
                                          Ty.apply
                                            (Ty.path "core::result::Result")
                                            []
                                            [
                                              Ty.path "argus_kernel::event::KernelEvent";
                                              Ty.path "argus_kernel::error::KernelError"
                                            ],
                                          M.get_trait_method (|
                                            "core::ops::try_trait::FromResidual",
                                            Ty.apply
                                              (Ty.path "core::result::Result")
                                              []
                                              [
                                                Ty.path "argus_kernel::event::KernelEvent";
                                                Ty.path "argus_kernel::error::KernelError"
                                              ],
                                            [],
                                            [
                                              Ty.apply
                                                (Ty.path "core::result::Result")
                                                []
                                                [
                                                  Ty.path "core::convert::Infallible";
                                                  Ty.path "argus_kernel::error::KernelError"
                                                ]
                                            ],
                                            "from_residual",
                                            [],
                                            []
                                          |),
                                          [ M.read (| residual |) ]
                                        |)
                                      |)
                                    |)
                                  |)));
                              fun γ =>
                                ltac:(M.monadic
                                  (let γ0_0 :=
                                    M.SubPointer.get_struct_tuple_field (|
                                      γ,
                                      "core::ops::control_flow::ControlFlow::Continue",
                                      0
                                    |) in
                                  let val := M.copy (| Ty.tuple [], γ0_0 |) in
                                  M.read (| val |)))
                            ]
                          |) in
                        let~ _ : Ty.tuple [] :=
                          M.write (|
                            M.SubPointer.get_struct_record_field (|
                              M.deref (| M.read (| self |) |),
                              "argus_kernel::kernel::Kernel",
                              "sequence"
                            |),
                            M.read (| next_seq |)
                          |) in
                        let~ _ : Ty.tuple [] :=
                          M.write (|
                            M.SubPointer.get_struct_record_field (|
                              M.deref (| M.read (| self |) |),
                              "argus_kernel::kernel::Kernel",
                              "state"
                            |),
                            M.read (| new_state |)
                          |) in
                        M.alloc (|
                          Ty.apply
                            (Ty.path "core::result::Result")
                            []
                            [
                              Ty.path "argus_kernel::event::KernelEvent";
                              Ty.path "argus_kernel::error::KernelError"
                            ],
                          Value.StructTuple
                            "core::result::Result::Ok"
                            []
                            [
                              Ty.path "argus_kernel::event::KernelEvent";
                              Ty.path "argus_kernel::error::KernelError"
                            ]
                            [ M.read (| event |) ]
                        |)
                      |)))
                ]
              |)))
          |)))
      | _, _, _ => M.impossible "wrong number of arguments"
      end.
    
    Global Instance AssociatedFunction_apply :
      forall (A C E : Ty.t),
      M.IsAssociatedFunction.C (Self A C E) "apply" (apply A C E).
    Admitted.
    Global Typeclasses Opaque apply.
    
    (*
        pub fn register_tool(&mut self, tool: ToolId) -> Result<KernelEvent, KernelError> {
            let result = transitions::register_tool(self.state.clone(), &self.background, tool);
            self.apply(result)
        }
    *)
    Definition register_tool
        (A C E : Ty.t)
        (ε : list Value.t)
        (τ : list Ty.t)
        (α : list Value.t)
        : M :=
      let Self : Ty.t := Self A C E in
      match ε, τ, α with
      | [], [], [ self; tool ] =>
        ltac:(M.monadic
          (let self :=
            M.alloc (|
              Ty.apply
                (Ty.path "&mut")
                []
                [ Ty.apply (Ty.path "argus_kernel::kernel::Kernel") [] [ A; C; E ] ],
              self
            |) in
          let tool := M.alloc (| Ty.path "argus_kernel::types::ToolId", tool |) in
          M.read (|
            let~ result :
                Ty.apply
                  (Ty.path "core::result::Result")
                  []
                  [
                    Ty.tuple
                      [
                        Ty.path "argus_kernel::state::KernelState";
                        Ty.path "argus_kernel::event::KernelAction"
                      ];
                    Ty.path "argus_kernel::error::KernelError"
                  ] :=
              M.call_closure (|
                Ty.apply
                  (Ty.path "core::result::Result")
                  []
                  [
                    Ty.tuple
                      [
                        Ty.path "argus_kernel::state::KernelState";
                        Ty.path "argus_kernel::event::KernelAction"
                      ];
                    Ty.path "argus_kernel::error::KernelError"
                  ],
                M.get_function (| "argus_kernel::transitions::register_tool", [], [] |),
                [
                  M.call_closure (|
                    Ty.path "argus_kernel::state::KernelState",
                    M.get_trait_method (|
                      "core::clone::Clone",
                      Ty.path "argus_kernel::state::KernelState",
                      [],
                      [],
                      "clone",
                      [],
                      []
                    |),
                    [
                      M.borrow (|
                        Pointer.Kind.Ref,
                        M.SubPointer.get_struct_record_field (|
                          M.deref (| M.read (| self |) |),
                          "argus_kernel::kernel::Kernel",
                          "state"
                        |)
                      |)
                    ]
                  |);
                  M.borrow (|
                    Pointer.Kind.Ref,
                    M.deref (|
                      M.borrow (|
                        Pointer.Kind.Ref,
                        M.SubPointer.get_struct_record_field (|
                          M.deref (| M.read (| self |) |),
                          "argus_kernel::kernel::Kernel",
                          "background"
                        |)
                      |)
                    |)
                  |);
                  M.read (| tool |)
                ]
              |) in
            M.alloc (|
              Ty.apply
                (Ty.path "core::result::Result")
                []
                [
                  Ty.path "argus_kernel::event::KernelEvent";
                  Ty.path "argus_kernel::error::KernelError"
                ],
              M.call_closure (|
                Ty.apply
                  (Ty.path "core::result::Result")
                  []
                  [
                    Ty.path "argus_kernel::event::KernelEvent";
                    Ty.path "argus_kernel::error::KernelError"
                  ],
                M.get_associated_function (|
                  Ty.apply (Ty.path "argus_kernel::kernel::Kernel") [] [ A; C; E ],
                  "apply",
                  [],
                  []
                |),
                [
                  M.borrow (| Pointer.Kind.MutRef, M.deref (| M.read (| self |) |) |);
                  M.read (| result |)
                ]
              |)
            |)
          |)))
      | _, _, _ => M.impossible "wrong number of arguments"
      end.
    
    Global Instance AssociatedFunction_register_tool :
      forall (A C E : Ty.t),
      M.IsAssociatedFunction.C (Self A C E) "register_tool" (register_tool A C E).
    Admitted.
    Global Typeclasses Opaque register_tool.
    
    (*
        pub fn delegate(
            &mut self,
            grantor: AgentId,
            grantee: AgentId,
        ) -> Result<KernelEvent, KernelError> {
            let result =
                transitions::delegate(self.state.clone(), &self.background, grantor, grantee);
            self.apply(result)
        }
    *)
    Definition delegate (A C E : Ty.t) (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
      let Self : Ty.t := Self A C E in
      match ε, τ, α with
      | [], [], [ self; grantor; grantee ] =>
        ltac:(M.monadic
          (let self :=
            M.alloc (|
              Ty.apply
                (Ty.path "&mut")
                []
                [ Ty.apply (Ty.path "argus_kernel::kernel::Kernel") [] [ A; C; E ] ],
              self
            |) in
          let grantor := M.alloc (| Ty.path "argus_kernel::types::AgentId", grantor |) in
          let grantee := M.alloc (| Ty.path "argus_kernel::types::AgentId", grantee |) in
          M.read (|
            let~ result :
                Ty.apply
                  (Ty.path "core::result::Result")
                  []
                  [
                    Ty.tuple
                      [
                        Ty.path "argus_kernel::state::KernelState";
                        Ty.path "argus_kernel::event::KernelAction"
                      ];
                    Ty.path "argus_kernel::error::KernelError"
                  ] :=
              M.call_closure (|
                Ty.apply
                  (Ty.path "core::result::Result")
                  []
                  [
                    Ty.tuple
                      [
                        Ty.path "argus_kernel::state::KernelState";
                        Ty.path "argus_kernel::event::KernelAction"
                      ];
                    Ty.path "argus_kernel::error::KernelError"
                  ],
                M.get_function (| "argus_kernel::transitions::delegate", [], [] |),
                [
                  M.call_closure (|
                    Ty.path "argus_kernel::state::KernelState",
                    M.get_trait_method (|
                      "core::clone::Clone",
                      Ty.path "argus_kernel::state::KernelState",
                      [],
                      [],
                      "clone",
                      [],
                      []
                    |),
                    [
                      M.borrow (|
                        Pointer.Kind.Ref,
                        M.SubPointer.get_struct_record_field (|
                          M.deref (| M.read (| self |) |),
                          "argus_kernel::kernel::Kernel",
                          "state"
                        |)
                      |)
                    ]
                  |);
                  M.borrow (|
                    Pointer.Kind.Ref,
                    M.deref (|
                      M.borrow (|
                        Pointer.Kind.Ref,
                        M.SubPointer.get_struct_record_field (|
                          M.deref (| M.read (| self |) |),
                          "argus_kernel::kernel::Kernel",
                          "background"
                        |)
                      |)
                    |)
                  |);
                  M.read (| grantor |);
                  M.read (| grantee |)
                ]
              |) in
            M.alloc (|
              Ty.apply
                (Ty.path "core::result::Result")
                []
                [
                  Ty.path "argus_kernel::event::KernelEvent";
                  Ty.path "argus_kernel::error::KernelError"
                ],
              M.call_closure (|
                Ty.apply
                  (Ty.path "core::result::Result")
                  []
                  [
                    Ty.path "argus_kernel::event::KernelEvent";
                    Ty.path "argus_kernel::error::KernelError"
                  ],
                M.get_associated_function (|
                  Ty.apply (Ty.path "argus_kernel::kernel::Kernel") [] [ A; C; E ],
                  "apply",
                  [],
                  []
                |),
                [
                  M.borrow (| Pointer.Kind.MutRef, M.deref (| M.read (| self |) |) |);
                  M.read (| result |)
                ]
              |)
            |)
          |)))
      | _, _, _ => M.impossible "wrong number of arguments"
      end.
    
    Global Instance AssociatedFunction_delegate :
      forall (A C E : Ty.t),
      M.IsAssociatedFunction.C (Self A C E) "delegate" (delegate A C E).
    Admitted.
    Global Typeclasses Opaque delegate.
    
    (*
        pub fn grant_capability(
            &mut self,
            parent: AgentId,
            child: AgentId,
            cap: CapKind,
        ) -> Result<KernelEvent, KernelError> {
            let result = transitions::grant_capability(
                self.state.clone(),
                &self.background,
                parent,
                child,
                cap,
            );
            self.apply(result)
        }
    *)
    Definition grant_capability
        (A C E : Ty.t)
        (ε : list Value.t)
        (τ : list Ty.t)
        (α : list Value.t)
        : M :=
      let Self : Ty.t := Self A C E in
      match ε, τ, α with
      | [], [], [ self; parent; child; cap ] =>
        ltac:(M.monadic
          (let self :=
            M.alloc (|
              Ty.apply
                (Ty.path "&mut")
                []
                [ Ty.apply (Ty.path "argus_kernel::kernel::Kernel") [] [ A; C; E ] ],
              self
            |) in
          let parent := M.alloc (| Ty.path "argus_kernel::types::AgentId", parent |) in
          let child := M.alloc (| Ty.path "argus_kernel::types::AgentId", child |) in
          let cap := M.alloc (| Ty.path "argus_kernel::capability::CapKind", cap |) in
          M.read (|
            let~ result :
                Ty.apply
                  (Ty.path "core::result::Result")
                  []
                  [
                    Ty.tuple
                      [
                        Ty.path "argus_kernel::state::KernelState";
                        Ty.path "argus_kernel::event::KernelAction"
                      ];
                    Ty.path "argus_kernel::error::KernelError"
                  ] :=
              M.call_closure (|
                Ty.apply
                  (Ty.path "core::result::Result")
                  []
                  [
                    Ty.tuple
                      [
                        Ty.path "argus_kernel::state::KernelState";
                        Ty.path "argus_kernel::event::KernelAction"
                      ];
                    Ty.path "argus_kernel::error::KernelError"
                  ],
                M.get_function (| "argus_kernel::transitions::grant_capability", [], [] |),
                [
                  M.call_closure (|
                    Ty.path "argus_kernel::state::KernelState",
                    M.get_trait_method (|
                      "core::clone::Clone",
                      Ty.path "argus_kernel::state::KernelState",
                      [],
                      [],
                      "clone",
                      [],
                      []
                    |),
                    [
                      M.borrow (|
                        Pointer.Kind.Ref,
                        M.SubPointer.get_struct_record_field (|
                          M.deref (| M.read (| self |) |),
                          "argus_kernel::kernel::Kernel",
                          "state"
                        |)
                      |)
                    ]
                  |);
                  M.borrow (|
                    Pointer.Kind.Ref,
                    M.deref (|
                      M.borrow (|
                        Pointer.Kind.Ref,
                        M.SubPointer.get_struct_record_field (|
                          M.deref (| M.read (| self |) |),
                          "argus_kernel::kernel::Kernel",
                          "background"
                        |)
                      |)
                    |)
                  |);
                  M.read (| parent |);
                  M.read (| child |);
                  M.read (| cap |)
                ]
              |) in
            M.alloc (|
              Ty.apply
                (Ty.path "core::result::Result")
                []
                [
                  Ty.path "argus_kernel::event::KernelEvent";
                  Ty.path "argus_kernel::error::KernelError"
                ],
              M.call_closure (|
                Ty.apply
                  (Ty.path "core::result::Result")
                  []
                  [
                    Ty.path "argus_kernel::event::KernelEvent";
                    Ty.path "argus_kernel::error::KernelError"
                  ],
                M.get_associated_function (|
                  Ty.apply (Ty.path "argus_kernel::kernel::Kernel") [] [ A; C; E ],
                  "apply",
                  [],
                  []
                |),
                [
                  M.borrow (| Pointer.Kind.MutRef, M.deref (| M.read (| self |) |) |);
                  M.read (| result |)
                ]
              |)
            |)
          |)))
      | _, _, _ => M.impossible "wrong number of arguments"
      end.
    
    Global Instance AssociatedFunction_grant_capability :
      forall (A C E : Ty.t),
      M.IsAssociatedFunction.C (Self A C E) "grant_capability" (grant_capability A C E).
    Admitted.
    Global Typeclasses Opaque grant_capability.
    
    (*
        pub fn revoke(
            &mut self,
            parent: AgentId,
            target: AgentId,
        ) -> Result<KernelEvent, KernelError> {
            let result =
                transitions::revoke(self.state.clone(), &self.background, parent, target);
            self.apply(result)
        }
    *)
    Definition revoke (A C E : Ty.t) (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
      let Self : Ty.t := Self A C E in
      match ε, τ, α with
      | [], [], [ self; parent; target ] =>
        ltac:(M.monadic
          (let self :=
            M.alloc (|
              Ty.apply
                (Ty.path "&mut")
                []
                [ Ty.apply (Ty.path "argus_kernel::kernel::Kernel") [] [ A; C; E ] ],
              self
            |) in
          let parent := M.alloc (| Ty.path "argus_kernel::types::AgentId", parent |) in
          let target := M.alloc (| Ty.path "argus_kernel::types::AgentId", target |) in
          M.read (|
            let~ result :
                Ty.apply
                  (Ty.path "core::result::Result")
                  []
                  [
                    Ty.tuple
                      [
                        Ty.path "argus_kernel::state::KernelState";
                        Ty.path "argus_kernel::event::KernelAction"
                      ];
                    Ty.path "argus_kernel::error::KernelError"
                  ] :=
              M.call_closure (|
                Ty.apply
                  (Ty.path "core::result::Result")
                  []
                  [
                    Ty.tuple
                      [
                        Ty.path "argus_kernel::state::KernelState";
                        Ty.path "argus_kernel::event::KernelAction"
                      ];
                    Ty.path "argus_kernel::error::KernelError"
                  ],
                M.get_function (| "argus_kernel::transitions::revoke", [], [] |),
                [
                  M.call_closure (|
                    Ty.path "argus_kernel::state::KernelState",
                    M.get_trait_method (|
                      "core::clone::Clone",
                      Ty.path "argus_kernel::state::KernelState",
                      [],
                      [],
                      "clone",
                      [],
                      []
                    |),
                    [
                      M.borrow (|
                        Pointer.Kind.Ref,
                        M.SubPointer.get_struct_record_field (|
                          M.deref (| M.read (| self |) |),
                          "argus_kernel::kernel::Kernel",
                          "state"
                        |)
                      |)
                    ]
                  |);
                  M.borrow (|
                    Pointer.Kind.Ref,
                    M.deref (|
                      M.borrow (|
                        Pointer.Kind.Ref,
                        M.SubPointer.get_struct_record_field (|
                          M.deref (| M.read (| self |) |),
                          "argus_kernel::kernel::Kernel",
                          "background"
                        |)
                      |)
                    |)
                  |);
                  M.read (| parent |);
                  M.read (| target |)
                ]
              |) in
            M.alloc (|
              Ty.apply
                (Ty.path "core::result::Result")
                []
                [
                  Ty.path "argus_kernel::event::KernelEvent";
                  Ty.path "argus_kernel::error::KernelError"
                ],
              M.call_closure (|
                Ty.apply
                  (Ty.path "core::result::Result")
                  []
                  [
                    Ty.path "argus_kernel::event::KernelEvent";
                    Ty.path "argus_kernel::error::KernelError"
                  ],
                M.get_associated_function (|
                  Ty.apply (Ty.path "argus_kernel::kernel::Kernel") [] [ A; C; E ],
                  "apply",
                  [],
                  []
                |),
                [
                  M.borrow (| Pointer.Kind.MutRef, M.deref (| M.read (| self |) |) |);
                  M.read (| result |)
                ]
              |)
            |)
          |)))
      | _, _, _ => M.impossible "wrong number of arguments"
      end.
    
    Global Instance AssociatedFunction_revoke :
      forall (A C E : Ty.t),
      M.IsAssociatedFunction.C (Self A C E) "revoke" (revoke A C E).
    Admitted.
    Global Typeclasses Opaque revoke.
    
    (*
        pub fn cascade_revoke(
            &mut self,
            child: AgentId,
            parent: AgentId,
        ) -> Result<KernelEvent, KernelError> {
            let result =
                transitions::cascade_revoke(self.state.clone(), &self.background, child, parent);
            self.apply(result)
        }
    *)
    Definition cascade_revoke
        (A C E : Ty.t)
        (ε : list Value.t)
        (τ : list Ty.t)
        (α : list Value.t)
        : M :=
      let Self : Ty.t := Self A C E in
      match ε, τ, α with
      | [], [], [ self; child; parent ] =>
        ltac:(M.monadic
          (let self :=
            M.alloc (|
              Ty.apply
                (Ty.path "&mut")
                []
                [ Ty.apply (Ty.path "argus_kernel::kernel::Kernel") [] [ A; C; E ] ],
              self
            |) in
          let child := M.alloc (| Ty.path "argus_kernel::types::AgentId", child |) in
          let parent := M.alloc (| Ty.path "argus_kernel::types::AgentId", parent |) in
          M.read (|
            let~ result :
                Ty.apply
                  (Ty.path "core::result::Result")
                  []
                  [
                    Ty.tuple
                      [
                        Ty.path "argus_kernel::state::KernelState";
                        Ty.path "argus_kernel::event::KernelAction"
                      ];
                    Ty.path "argus_kernel::error::KernelError"
                  ] :=
              M.call_closure (|
                Ty.apply
                  (Ty.path "core::result::Result")
                  []
                  [
                    Ty.tuple
                      [
                        Ty.path "argus_kernel::state::KernelState";
                        Ty.path "argus_kernel::event::KernelAction"
                      ];
                    Ty.path "argus_kernel::error::KernelError"
                  ],
                M.get_function (| "argus_kernel::transitions::cascade_revoke", [], [] |),
                [
                  M.call_closure (|
                    Ty.path "argus_kernel::state::KernelState",
                    M.get_trait_method (|
                      "core::clone::Clone",
                      Ty.path "argus_kernel::state::KernelState",
                      [],
                      [],
                      "clone",
                      [],
                      []
                    |),
                    [
                      M.borrow (|
                        Pointer.Kind.Ref,
                        M.SubPointer.get_struct_record_field (|
                          M.deref (| M.read (| self |) |),
                          "argus_kernel::kernel::Kernel",
                          "state"
                        |)
                      |)
                    ]
                  |);
                  M.borrow (|
                    Pointer.Kind.Ref,
                    M.deref (|
                      M.borrow (|
                        Pointer.Kind.Ref,
                        M.SubPointer.get_struct_record_field (|
                          M.deref (| M.read (| self |) |),
                          "argus_kernel::kernel::Kernel",
                          "background"
                        |)
                      |)
                    |)
                  |);
                  M.read (| child |);
                  M.read (| parent |)
                ]
              |) in
            M.alloc (|
              Ty.apply
                (Ty.path "core::result::Result")
                []
                [
                  Ty.path "argus_kernel::event::KernelEvent";
                  Ty.path "argus_kernel::error::KernelError"
                ],
              M.call_closure (|
                Ty.apply
                  (Ty.path "core::result::Result")
                  []
                  [
                    Ty.path "argus_kernel::event::KernelEvent";
                    Ty.path "argus_kernel::error::KernelError"
                  ],
                M.get_associated_function (|
                  Ty.apply (Ty.path "argus_kernel::kernel::Kernel") [] [ A; C; E ],
                  "apply",
                  [],
                  []
                |),
                [
                  M.borrow (| Pointer.Kind.MutRef, M.deref (| M.read (| self |) |) |);
                  M.read (| result |)
                ]
              |)
            |)
          |)))
      | _, _, _ => M.impossible "wrong number of arguments"
      end.
    
    Global Instance AssociatedFunction_cascade_revoke :
      forall (A C E : Ty.t),
      M.IsAssociatedFunction.C (Self A C E) "cascade_revoke" (cascade_revoke A C E).
    Admitted.
    Global Typeclasses Opaque cascade_revoke.
    
    (*
        pub fn invoke_start(
            &mut self,
            agent: AgentId,
            tool: ToolId,
            inv: InvocationId,
        ) -> Result<KernelEvent, KernelError> {
            let result = transitions::invoke_start(
                self.state.clone(),
                &self.background,
                &self.authorizer,
                &self.content_gate,
                agent,
                tool,
                inv,
            );
            self.apply(result)
        }
    *)
    Definition invoke_start
        (A C E : Ty.t)
        (ε : list Value.t)
        (τ : list Ty.t)
        (α : list Value.t)
        : M :=
      let Self : Ty.t := Self A C E in
      match ε, τ, α with
      | [], [], [ self; agent; tool; inv ] =>
        ltac:(M.monadic
          (let self :=
            M.alloc (|
              Ty.apply
                (Ty.path "&mut")
                []
                [ Ty.apply (Ty.path "argus_kernel::kernel::Kernel") [] [ A; C; E ] ],
              self
            |) in
          let agent := M.alloc (| Ty.path "argus_kernel::types::AgentId", agent |) in
          let tool := M.alloc (| Ty.path "argus_kernel::types::ToolId", tool |) in
          let inv := M.alloc (| Ty.path "argus_kernel::types::InvocationId", inv |) in
          M.read (|
            let~ result :
                Ty.apply
                  (Ty.path "core::result::Result")
                  []
                  [
                    Ty.tuple
                      [
                        Ty.path "argus_kernel::state::KernelState";
                        Ty.path "argus_kernel::event::KernelAction"
                      ];
                    Ty.path "argus_kernel::error::KernelError"
                  ] :=
              M.call_closure (|
                Ty.apply
                  (Ty.path "core::result::Result")
                  []
                  [
                    Ty.tuple
                      [
                        Ty.path "argus_kernel::state::KernelState";
                        Ty.path "argus_kernel::event::KernelAction"
                      ];
                    Ty.path "argus_kernel::error::KernelError"
                  ],
                M.get_function (| "argus_kernel::transitions::invoke_start", [], [ A; C ] |),
                [
                  M.call_closure (|
                    Ty.path "argus_kernel::state::KernelState",
                    M.get_trait_method (|
                      "core::clone::Clone",
                      Ty.path "argus_kernel::state::KernelState",
                      [],
                      [],
                      "clone",
                      [],
                      []
                    |),
                    [
                      M.borrow (|
                        Pointer.Kind.Ref,
                        M.SubPointer.get_struct_record_field (|
                          M.deref (| M.read (| self |) |),
                          "argus_kernel::kernel::Kernel",
                          "state"
                        |)
                      |)
                    ]
                  |);
                  M.borrow (|
                    Pointer.Kind.Ref,
                    M.deref (|
                      M.borrow (|
                        Pointer.Kind.Ref,
                        M.SubPointer.get_struct_record_field (|
                          M.deref (| M.read (| self |) |),
                          "argus_kernel::kernel::Kernel",
                          "background"
                        |)
                      |)
                    |)
                  |);
                  M.borrow (|
                    Pointer.Kind.Ref,
                    M.deref (|
                      M.borrow (|
                        Pointer.Kind.Ref,
                        M.SubPointer.get_struct_record_field (|
                          M.deref (| M.read (| self |) |),
                          "argus_kernel::kernel::Kernel",
                          "authorizer"
                        |)
                      |)
                    |)
                  |);
                  M.borrow (|
                    Pointer.Kind.Ref,
                    M.deref (|
                      M.borrow (|
                        Pointer.Kind.Ref,
                        M.SubPointer.get_struct_record_field (|
                          M.deref (| M.read (| self |) |),
                          "argus_kernel::kernel::Kernel",
                          "content_gate"
                        |)
                      |)
                    |)
                  |);
                  M.read (| agent |);
                  M.read (| tool |);
                  M.read (| inv |)
                ]
              |) in
            M.alloc (|
              Ty.apply
                (Ty.path "core::result::Result")
                []
                [
                  Ty.path "argus_kernel::event::KernelEvent";
                  Ty.path "argus_kernel::error::KernelError"
                ],
              M.call_closure (|
                Ty.apply
                  (Ty.path "core::result::Result")
                  []
                  [
                    Ty.path "argus_kernel::event::KernelEvent";
                    Ty.path "argus_kernel::error::KernelError"
                  ],
                M.get_associated_function (|
                  Ty.apply (Ty.path "argus_kernel::kernel::Kernel") [] [ A; C; E ],
                  "apply",
                  [],
                  []
                |),
                [
                  M.borrow (| Pointer.Kind.MutRef, M.deref (| M.read (| self |) |) |);
                  M.read (| result |)
                ]
              |)
            |)
          |)))
      | _, _, _ => M.impossible "wrong number of arguments"
      end.
    
    Global Instance AssociatedFunction_invoke_start :
      forall (A C E : Ty.t),
      M.IsAssociatedFunction.C (Self A C E) "invoke_start" (invoke_start A C E).
    Admitted.
    Global Typeclasses Opaque invoke_start.
    
    (*
        pub fn invoke_complete(
            &mut self,
            agent: AgentId,
            inv: InvocationId,
        ) -> Result<KernelEvent, KernelError> {
            let result =
                transitions::invoke_complete(self.state.clone(), &self.background, agent, inv);
            self.apply(result)
        }
    *)
    Definition invoke_complete
        (A C E : Ty.t)
        (ε : list Value.t)
        (τ : list Ty.t)
        (α : list Value.t)
        : M :=
      let Self : Ty.t := Self A C E in
      match ε, τ, α with
      | [], [], [ self; agent; inv ] =>
        ltac:(M.monadic
          (let self :=
            M.alloc (|
              Ty.apply
                (Ty.path "&mut")
                []
                [ Ty.apply (Ty.path "argus_kernel::kernel::Kernel") [] [ A; C; E ] ],
              self
            |) in
          let agent := M.alloc (| Ty.path "argus_kernel::types::AgentId", agent |) in
          let inv := M.alloc (| Ty.path "argus_kernel::types::InvocationId", inv |) in
          M.read (|
            let~ result :
                Ty.apply
                  (Ty.path "core::result::Result")
                  []
                  [
                    Ty.tuple
                      [
                        Ty.path "argus_kernel::state::KernelState";
                        Ty.path "argus_kernel::event::KernelAction"
                      ];
                    Ty.path "argus_kernel::error::KernelError"
                  ] :=
              M.call_closure (|
                Ty.apply
                  (Ty.path "core::result::Result")
                  []
                  [
                    Ty.tuple
                      [
                        Ty.path "argus_kernel::state::KernelState";
                        Ty.path "argus_kernel::event::KernelAction"
                      ];
                    Ty.path "argus_kernel::error::KernelError"
                  ],
                M.get_function (| "argus_kernel::transitions::invoke_complete", [], [] |),
                [
                  M.call_closure (|
                    Ty.path "argus_kernel::state::KernelState",
                    M.get_trait_method (|
                      "core::clone::Clone",
                      Ty.path "argus_kernel::state::KernelState",
                      [],
                      [],
                      "clone",
                      [],
                      []
                    |),
                    [
                      M.borrow (|
                        Pointer.Kind.Ref,
                        M.SubPointer.get_struct_record_field (|
                          M.deref (| M.read (| self |) |),
                          "argus_kernel::kernel::Kernel",
                          "state"
                        |)
                      |)
                    ]
                  |);
                  M.borrow (|
                    Pointer.Kind.Ref,
                    M.deref (|
                      M.borrow (|
                        Pointer.Kind.Ref,
                        M.SubPointer.get_struct_record_field (|
                          M.deref (| M.read (| self |) |),
                          "argus_kernel::kernel::Kernel",
                          "background"
                        |)
                      |)
                    |)
                  |);
                  M.read (| agent |);
                  M.read (| inv |)
                ]
              |) in
            M.alloc (|
              Ty.apply
                (Ty.path "core::result::Result")
                []
                [
                  Ty.path "argus_kernel::event::KernelEvent";
                  Ty.path "argus_kernel::error::KernelError"
                ],
              M.call_closure (|
                Ty.apply
                  (Ty.path "core::result::Result")
                  []
                  [
                    Ty.path "argus_kernel::event::KernelEvent";
                    Ty.path "argus_kernel::error::KernelError"
                  ],
                M.get_associated_function (|
                  Ty.apply (Ty.path "argus_kernel::kernel::Kernel") [] [ A; C; E ],
                  "apply",
                  [],
                  []
                |),
                [
                  M.borrow (| Pointer.Kind.MutRef, M.deref (| M.read (| self |) |) |);
                  M.read (| result |)
                ]
              |)
            |)
          |)))
      | _, _, _ => M.impossible "wrong number of arguments"
      end.
    
    Global Instance AssociatedFunction_invoke_complete :
      forall (A C E : Ty.t),
      M.IsAssociatedFunction.C (Self A C E) "invoke_complete" (invoke_complete A C E).
    Admitted.
    Global Typeclasses Opaque invoke_complete.
    
    (*
        pub fn return_endorsed(
            &mut self,
            child: AgentId,
            parent: AgentId,
        ) -> Result<KernelEvent, KernelError> {
            let result =
                transitions::return_endorsed(self.state.clone(), &self.background, child, parent);
            self.apply(result)
        }
    *)
    Definition return_endorsed
        (A C E : Ty.t)
        (ε : list Value.t)
        (τ : list Ty.t)
        (α : list Value.t)
        : M :=
      let Self : Ty.t := Self A C E in
      match ε, τ, α with
      | [], [], [ self; child; parent ] =>
        ltac:(M.monadic
          (let self :=
            M.alloc (|
              Ty.apply
                (Ty.path "&mut")
                []
                [ Ty.apply (Ty.path "argus_kernel::kernel::Kernel") [] [ A; C; E ] ],
              self
            |) in
          let child := M.alloc (| Ty.path "argus_kernel::types::AgentId", child |) in
          let parent := M.alloc (| Ty.path "argus_kernel::types::AgentId", parent |) in
          M.read (|
            let~ result :
                Ty.apply
                  (Ty.path "core::result::Result")
                  []
                  [
                    Ty.tuple
                      [
                        Ty.path "argus_kernel::state::KernelState";
                        Ty.path "argus_kernel::event::KernelAction"
                      ];
                    Ty.path "argus_kernel::error::KernelError"
                  ] :=
              M.call_closure (|
                Ty.apply
                  (Ty.path "core::result::Result")
                  []
                  [
                    Ty.tuple
                      [
                        Ty.path "argus_kernel::state::KernelState";
                        Ty.path "argus_kernel::event::KernelAction"
                      ];
                    Ty.path "argus_kernel::error::KernelError"
                  ],
                M.get_function (| "argus_kernel::transitions::return_endorsed", [], [] |),
                [
                  M.call_closure (|
                    Ty.path "argus_kernel::state::KernelState",
                    M.get_trait_method (|
                      "core::clone::Clone",
                      Ty.path "argus_kernel::state::KernelState",
                      [],
                      [],
                      "clone",
                      [],
                      []
                    |),
                    [
                      M.borrow (|
                        Pointer.Kind.Ref,
                        M.SubPointer.get_struct_record_field (|
                          M.deref (| M.read (| self |) |),
                          "argus_kernel::kernel::Kernel",
                          "state"
                        |)
                      |)
                    ]
                  |);
                  M.borrow (|
                    Pointer.Kind.Ref,
                    M.deref (|
                      M.borrow (|
                        Pointer.Kind.Ref,
                        M.SubPointer.get_struct_record_field (|
                          M.deref (| M.read (| self |) |),
                          "argus_kernel::kernel::Kernel",
                          "background"
                        |)
                      |)
                    |)
                  |);
                  M.read (| child |);
                  M.read (| parent |)
                ]
              |) in
            M.alloc (|
              Ty.apply
                (Ty.path "core::result::Result")
                []
                [
                  Ty.path "argus_kernel::event::KernelEvent";
                  Ty.path "argus_kernel::error::KernelError"
                ],
              M.call_closure (|
                Ty.apply
                  (Ty.path "core::result::Result")
                  []
                  [
                    Ty.path "argus_kernel::event::KernelEvent";
                    Ty.path "argus_kernel::error::KernelError"
                  ],
                M.get_associated_function (|
                  Ty.apply (Ty.path "argus_kernel::kernel::Kernel") [] [ A; C; E ],
                  "apply",
                  [],
                  []
                |),
                [
                  M.borrow (| Pointer.Kind.MutRef, M.deref (| M.read (| self |) |) |);
                  M.read (| result |)
                ]
              |)
            |)
          |)))
      | _, _, _ => M.impossible "wrong number of arguments"
      end.
    
    Global Instance AssociatedFunction_return_endorsed :
      forall (A C E : Ty.t),
      M.IsAssociatedFunction.C (Self A C E) "return_endorsed" (return_endorsed A C E).
    Admitted.
    Global Typeclasses Opaque return_endorsed.
    
    (*
        pub fn return_unendorsed(
            &mut self,
            child: AgentId,
            parent: AgentId,
        ) -> Result<KernelEvent, KernelError> {
            let result = transitions::return_unendorsed(
                self.state.clone(),
                &self.background,
                &self.content_gate,
                child,
                parent,
            );
            self.apply(result)
        }
    *)
    Definition return_unendorsed
        (A C E : Ty.t)
        (ε : list Value.t)
        (τ : list Ty.t)
        (α : list Value.t)
        : M :=
      let Self : Ty.t := Self A C E in
      match ε, τ, α with
      | [], [], [ self; child; parent ] =>
        ltac:(M.monadic
          (let self :=
            M.alloc (|
              Ty.apply
                (Ty.path "&mut")
                []
                [ Ty.apply (Ty.path "argus_kernel::kernel::Kernel") [] [ A; C; E ] ],
              self
            |) in
          let child := M.alloc (| Ty.path "argus_kernel::types::AgentId", child |) in
          let parent := M.alloc (| Ty.path "argus_kernel::types::AgentId", parent |) in
          M.read (|
            let~ result :
                Ty.apply
                  (Ty.path "core::result::Result")
                  []
                  [
                    Ty.tuple
                      [
                        Ty.path "argus_kernel::state::KernelState";
                        Ty.path "argus_kernel::event::KernelAction"
                      ];
                    Ty.path "argus_kernel::error::KernelError"
                  ] :=
              M.call_closure (|
                Ty.apply
                  (Ty.path "core::result::Result")
                  []
                  [
                    Ty.tuple
                      [
                        Ty.path "argus_kernel::state::KernelState";
                        Ty.path "argus_kernel::event::KernelAction"
                      ];
                    Ty.path "argus_kernel::error::KernelError"
                  ],
                M.get_function (| "argus_kernel::transitions::return_unendorsed", [], [ C ] |),
                [
                  M.call_closure (|
                    Ty.path "argus_kernel::state::KernelState",
                    M.get_trait_method (|
                      "core::clone::Clone",
                      Ty.path "argus_kernel::state::KernelState",
                      [],
                      [],
                      "clone",
                      [],
                      []
                    |),
                    [
                      M.borrow (|
                        Pointer.Kind.Ref,
                        M.SubPointer.get_struct_record_field (|
                          M.deref (| M.read (| self |) |),
                          "argus_kernel::kernel::Kernel",
                          "state"
                        |)
                      |)
                    ]
                  |);
                  M.borrow (|
                    Pointer.Kind.Ref,
                    M.deref (|
                      M.borrow (|
                        Pointer.Kind.Ref,
                        M.SubPointer.get_struct_record_field (|
                          M.deref (| M.read (| self |) |),
                          "argus_kernel::kernel::Kernel",
                          "background"
                        |)
                      |)
                    |)
                  |);
                  M.borrow (|
                    Pointer.Kind.Ref,
                    M.deref (|
                      M.borrow (|
                        Pointer.Kind.Ref,
                        M.SubPointer.get_struct_record_field (|
                          M.deref (| M.read (| self |) |),
                          "argus_kernel::kernel::Kernel",
                          "content_gate"
                        |)
                      |)
                    |)
                  |);
                  M.read (| child |);
                  M.read (| parent |)
                ]
              |) in
            M.alloc (|
              Ty.apply
                (Ty.path "core::result::Result")
                []
                [
                  Ty.path "argus_kernel::event::KernelEvent";
                  Ty.path "argus_kernel::error::KernelError"
                ],
              M.call_closure (|
                Ty.apply
                  (Ty.path "core::result::Result")
                  []
                  [
                    Ty.path "argus_kernel::event::KernelEvent";
                    Ty.path "argus_kernel::error::KernelError"
                  ],
                M.get_associated_function (|
                  Ty.apply (Ty.path "argus_kernel::kernel::Kernel") [] [ A; C; E ],
                  "apply",
                  [],
                  []
                |),
                [
                  M.borrow (| Pointer.Kind.MutRef, M.deref (| M.read (| self |) |) |);
                  M.read (| result |)
                ]
              |)
            |)
          |)))
      | _, _, _ => M.impossible "wrong number of arguments"
      end.
    
    Global Instance AssociatedFunction_return_unendorsed :
      forall (A C E : Ty.t),
      M.IsAssociatedFunction.C (Self A C E) "return_unendorsed" (return_unendorsed A C E).
    Admitted.
    Global Typeclasses Opaque return_unendorsed.
  End Impl_argus_kernel_kernel_Kernel_A_C_E.
End kernel.
