(* Generated by rocq-of-rust *)
Require Import RocqOfRust.RocqOfRust.

Module traits.
  (* Trait *)
  (* Empty module 'AuthorizerOracle' *)
  
  (* Trait *)
  (* Empty module 'ContentGateOracle' *)
  
  (* Trait *)
  (* Empty module 'EventStore' *)
End traits.
