name = "kav"
defaultTargets = ["Kav"]

[[require]]
name = "auto"
git = "https://github.com/leanprover-community/lean-auto.git"
rev = "v4.30.0-hammer"

[[require]]
name = "Duper"
git = "https://github.com/leanprover-community/duper.git"
rev = "v4.30.0"

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "v4.30.0"

[[lean_lib]]
name = "Kav"

[[lean_lib]]
name = "KavTest"
globs = ["KavTest"]
